# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 11:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_iotd', '0004_add_iotddismissedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPickArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrobin.Image', unique=True)),
            ],
            options={
                'ordering': ['-image__published'],
            },
        ),
        migrations.CreateModel(
            name='TopPickNominationsArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrobin.Image', unique=True)),
            ],
            options={
                'ordering': ['-image__published'],
            },
        ),
    ]
