# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-23 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0005_toppickarchive_toppicknominationsarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdsubmission',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iotdvote',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toppickarchive',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astrobin.Image'),
        ),
        migrations.AlterField(
            model_name='toppicknominationsarchive',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astrobin.Image'),
        ),
    ]
