# Generated by Django 2.2.24 on 2021-12-09 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_iotd', '0006_add_cascades_and_fix_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotdStaffMemberSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_sort_order', models.CharField(
                    choices=[('NEWEST_FIRST', 'Newest first'), ('OLDEST_FIRST', 'Oldest first')],
                    default='NEWEST_FIRST', max_length=16
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, related_name='iotd_staff_member_settings',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
