# Generated by Django 2.2.24 on 2021-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0007_iotdstaffmembersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdstaffmembersettings',
            name='hidden_appear_last',
            field=models.BooleanField(default=True),
        ),
    ]
