# Generated by Django 2.2.24 on 2023-06-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0011_add_data_source_totals_to_iotd_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdstats',
            old_name='total_traveler_images',
            new_name='total_traveller_images',
        ),
    ]
