# Generated by Django 2.2.24 on 2023-06-30 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0012_iotd_stats_rename_total_traveler_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 6, 29)),
            preserve_default=False,
        ),
    ]
