# Generated by Django 2.2.24 on 2023-06-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0013_iotdstats_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdstats',
            options={'ordering': ('-created',)},
        ),
    ]
