# Generated by Django 2.2.24 on 2023-11-07 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0018_fix_wasted_promotions_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdstaffmemberscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iotd_staff_member_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
