# Generated by Django 2.2.24 on 2024-01-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0020_add_periods_activity_days_promotions_dismissals_ratio_to_iotd_staff_member_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdstats',
            name='landscape_tpns',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdstats',
            name='landscape_tps',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdstats',
            name='landscape_iotds',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdstats',
            name='total_landscape_images',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
