# Generated by Django 2.2.24 on 2024-07-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0022_iotdreviewerseenimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdstats',
            name='artificial_satellite_iotds',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdstats',
            name='artificial_satellite_tpns',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdstats',
            name='artificial_satellite_tps',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdstats',
            name='total_artificial_satellite_images',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
