# Generated by Django 2.2.24 on 2024-08-30 08:09

from django.db import migrations, models
import django.utils.timezone


def set_created_to_published(apps, schema_editor):
    TopPickNominationsArchive = apps.get_model('astrobin_apps_iotd', 'TopPickNominationsArchive')
    for entry in TopPickNominationsArchive.objects.all().select_related('image'):
        entry.created = entry.image.published
        entry.save()

    TopPickArchive = apps.get_model('astrobin_apps_iotd', 'TopPickArchive')
    for entry in TopPickArchive.objects.all().select_related('image'):
        entry.created = entry.image.published
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_iotd', '0023_add_support_for_artificial_satellite_subject_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppickarchive',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='toppicknominationsarchive',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='toppickarchive',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppicknominationsarchive',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_created_to_published),
    ]
