# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-17 10:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0003_auto_20180217_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
