# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-24 16:57


from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0005_auto_20180224_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', tinymce.models.HTMLField()),
            ],
        ),
    ]
