# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 07:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0007_auto_20180225_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
