# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 19:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0008_auto_20180228_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
