# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-03 06:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0009_userprofile_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
