# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 19:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0010_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data_source',
            field=models.CharField(choices=[(None, '---------'), ('Self acquired', (('BACKYARD', 'Backyard'), ('TRAVELLER', 'Traveller'), ('OWN_REMOTE', 'Own remote observatory'))), ('Downloaded', (('AMATEUR_HOSTING', 'Amateur hosting facility'), ('PUBLIC_AMATEUR_DATA', 'Public amateur data'), ('PRO_DATA', 'Professional, scientific grade data'))), ('Other', (('MIX', 'Mix of multiple sources'), ('OTHER', 'None of the above'), ('UNKNOWN', 'Unknown')))], default=b'UNKNOWN', help_text='Where does the data for this image come from?', max_length=32, verbose_name='Data source'),
        ),
    ]
