# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-02 16:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0013_auto_20181124_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='remote_source',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('AstroCamp', 'AC'), ('Dark Sky Portal', 'DSP'), ('DeepSkyChile', 'DSC'), ('DeepSkyWest', 'DSW'), ('e-EyE Extremadura', 'eEyE'), ('Grand Mesa Observatory', 'GME'), ("Heaven's Mirror Observatory", 'HMO'), ('IC Astronomy Observatories', 'IC'), ('Image The Universe', 'ITU'), ('iTelescope', 'iT'), ('New Mexico Skies', 'NMS'), ('Observatorio El Sauce', 'OES'), ('Riverland Dingo Observatory', 'RLD'), ('Sahara Sky', 'SS'), ('San Pedro Valley Observatory', 'SPV'), ('Sierra Remote Observatories', 'SRO'), ('SkyPi Online Observatory', 'SPOO')], help_text='Which remote hosting facility did you use to acquire data for this image?', max_length=8, null=True, verbose_name='Remote data source'),
        ),
    ]
