# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-04 19:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0016_auto_20181203_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='remote_source',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('OWN', 'Non-commercial independent facility'), (None, '---------'), ('AC', 'AstroCamp'), ('CS', 'ChileScope'), ('DSP', 'Dark Sky Portal'), ('DSC', 'DeepSkyChile'), ('DSW', 'DeepSkyWest'), ('eEyE', 'e-EyE Extremadura'), ('GMO', 'Grand Mesa Observatory'), ('HMO', "Heaven's Mirror Observatory"), ('IC', 'IC Astronomy Observatories'), ('ITU', 'Image The Universe'), ('iT', 'iTelescope'), ('NMS', 'New Mexico Skies'), ('OES', 'Observatorio El Sauce'), ('RLD', 'Riverland Dingo Observatory'), ('SS', 'Sahara Sky'), ('SPVO', 'San Pedro Valley Observatory'), ('SRO', 'Sierra Remote Observatories'), ('SRO2', 'Sky Ranch Observatory'), ('SPOO', 'SkyPi Online Observatory'), ('OTHER', 'None of the above')], help_text='Which remote hosting facility did you use to acquire data for this image?', max_length=8, null=True, verbose_name='Remote data source'),
        ),
    ]
