# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0020_auto_20190118_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='focal_ratio',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The Focal ratio of the optical system (in f-stops). Eg: 4.5', max_digits=3, null=True, verbose_name='Focal ratio'),
        ),
        migrations.AlterField(
            model_name='solarsystem_acquisition',
            name='focal_ratio',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The Focal ratio of the optical system (in f-stops). Eg: 4.5', max_digits=3, null=True, verbose_name='Focal ratio'),
        ),
    ]
