# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0022_auto_20190617_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(default=None, max_length=6, null=True, unique=True),
        ),
    ]
