# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-11 08:06
from __future__ import unicode_literals

import astrobin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0023_auto_20190811_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hash',
            field=models.CharField(default=astrobin.models.image_hash, max_length=6, null=True, unique=True),
        ),
    ]
