# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-11 08:06


from astrobin.models import Image
from django.db import migrations, models

from astrobin.utils import generate_unique_hash


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0023_auto_20190811_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hash',
            field=models.CharField(
                default=lambda: generate_unique_hash(6, Image.all_objects),
                max_length=6,
                null=True,
                unique=True
            ),
        ),
    ]
