# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0024_auto_20190811_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_offer',
            field=models.CharField(blank=True, default=None, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_offer_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_offer_sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
