# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-30 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0025_premium_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastemail',
            name='message_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='broadcastemail',
            name='message',
            field=models.TextField(),
        ),
    ]
