# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0029_add_image_revision_mouse_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Gain'),
        ),
    ]
