# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0030_extend_gain_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='order_by_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order by image tag'),
        ),
    ]
