# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0031_add_collection_order_by_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='skip_notifications',
            field=models.BooleanField(default=False, help_text='Do not notify your followers about this image upload.', verbose_name='Skip notifications'),
        ),
    ]
