# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-05 16:15
from __future__ import unicode_literals

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0032_add_skip_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='square_cropping',
            field=image_cropping.fields.ImageRatioField(
                b'image_file', '130x130', adapt_rotation=False, allow_fullsize=False, free_crop=False,
                help_text='Select an area of the image to be used as thumbnail in your gallery.',
                hide_image_field=False, size_warning=False, verbose_name='Gallery thumbnail'),
        ),
    ]
