# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-11 08:38


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0036_migrate_gear_types_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('REFR ACHRO', 'Refractor: achromatic'),
                    ('REFR SEMI-APO', 'Refractor: semi-apochromatic'),
                    ('REFR APO', 'Refractor: apochromatic'),
                    ('REFR NON-ACHRO GALILEAN', 'Refractor: non-achromatic Galilean'),
                    ('REFR NON-ACHRO KEPLERIAN', 'Refractor: non-achromatic Keplerian'),
                    ('REFR SUPERACHRO', 'Refractor: superachromat'),
                    ('REFL DALL-KIRKHAM', 'Reflector: Dall-Kirkham'),
                    ('REFL NASMYTH', 'Reflector: Nasmyth'),
                    ('REFL RITCHEY CHRETIEN', 'Reflector: Ritchey Chretien'),
                    ('REFL GREGORIAN', 'Reflector: Gregorian'),
                    ('REFL HERSCHELLIAN', 'Reflector: Herschellian'),
                    ('REFL NEWTONIAN', 'Reflector: Newtonian'),
                    ('CATA ARGUNOV-CASSEGRAIN', 'Catadioptric: Argunov-Cassegrain'),
                    ('CATA KLEVTSOV-CASSEGRAIN', 'Catadioptric: Klevtsov-Cassegrain'),
                    ('CATA LURIE-HOUGHTON', 'Catadioptric: Lurie-Houghton'),
                    ('CATA MAKSUTOV', 'Catadioptric: Maksutov'),
                    ('CATA MAKSUTOV-CASSEGRAIN', 'Catadioptric: Maksutov-Cassegrain'),
                    ('CATA MOD DALL-KIRKHAM', 'Catadioptric: modified Dall-Kirkham'),
                    ('CATA SCHMIDT CAMERA', 'Catadioptric: Schmidt camera'),
                    ('CATA SCHMIDT-CASSEGRAIN', 'Catadioptric: Schmidt-Cassegrain'),
                    ('CATA ACF SCHMIDT-CASSEGRAIN', 'Catadioptric: ACF Schmidt-Cassegrain'),
                    ('CATA ROWE-ACKERMANN SCHMIDT', 'Catadioptric: Rowe-Atkinson Schmidt astrograph'),
                    ('CAMERA LENS', 'Camera lens'),
                    ('BINOCULARS', 'Binoculars')
                ],
                max_length=64,
                null=True,
                verbose_name='Type'),
        ),
    ]
