# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0036_migrate_gear_types_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    (b'REFR ACHRO', 'Refractor: achromatic'),
                    (b'REFR SEMI-APO', 'Refractor: semi-apochromatic'),
                    (b'REFR APO', 'Refractor: apochromatic'),
                    (b'REFR NON-ACHRO GALILEAN', 'Refractor: non-achromatic Galilean'),
                    (b'REFR NON-ACHRO KEPLERIAN', 'Refractor: non-achromatic Keplerian'),
                    (b'REFR SUPERACHRO', 'Refractor: superachromat'),
                    (b'REFL DALL-KIRKHAM', 'Reflector: Dall-Kirkham'),
                    (b'REFL NASMYTH', 'Reflector: Nasmyth'),
                    (b'REFL RITCHEY CHRETIEN', 'Reflector: Ritchey Chretien'),
                    (b'REFL GREGORIAN', 'Reflector: Gregorian'),
                    (b'REFL HERSCHELLIAN', 'Reflector: Herschellian'),
                    (b'REFL NEWTONIAN', 'Reflector: Newtonian'),
                    (b'CATA ARGUNOV-CASSEGRAIN', 'Catadioptric: Argunov-Cassegrain'),
                    (b'CATA KLEVTSOV-CASSEGRAIN', 'Catadioptric: Klevtsov-Cassegrain'),
                    (b'CATA LURIE-HOUGHTON', 'Catadioptric: Lurie-Houghton'),
                    (b'CATA MAKSUTOV', 'Catadioptric: Maksutov'),
                    (b'CATA MAKSUTOV-CASSEGRAIN', 'Catadioptric: Maksutov-Cassegrain'),
                    (b'CATA MOD DALL-KIRKHAM', 'Catadioptric: modified Dall-Kirkham'),
                    (b'CATA SCHMIDT CAMERA', 'Catadioptric: Schmidt camera'),
                    (b'CATA SCHMIDT-CASSEGRAIN', 'Catadioptric: Schmidt-Cassegrain'),
                    (b'CATA ACF SCHMIDT-CASSEGRAIN', 'Catadioptric: ACF Schmidt-Cassegrain'),
                    (b'CATA ROWE-ACKERMANN SCHMIDT', 'Catadioptric: Rowe-Atkinson Schmidt astrograph'),
                    (b'CAMERA LENS', 'Camera lens'),
                    (b'BINOCULARS', 'Binoculars')
                ],
                max_length=64,
                null=True,
                verbose_name='Type'),
        ),
    ]
