# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0037_add_rowe_ackermann_schmidt_telescope_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem_acquisition',
            name='seeing',
            field=models.IntegerField(
                blank=True,
                help_text='Your estimation of the seeing, on a scale from 1 to 5. Larger is better.',
                null=True,
                verbose_name='Seeing'),
        ),
        migrations.AlterField(
            model_name='solarsystem_acquisition',
            name='transparency',
            field=models.IntegerField(
                blank=True,
                help_text='Your estimation of the transparency, on a scale from 1 to 10. Larger is better.',
                null=True,
                verbose_name='Transparency'),
        ),
    ]
