# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0038_update_seeing_and_transparency_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='corrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='corrupted',
            field=models.BooleanField(default=False),
        ),
    ]
