# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models

import astrobin.models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0039_add_allow_astronomy_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fits_file',
            field=models.ImageField(max_length=256, null=True, upload_to=astrobin.models.image_upload_path),
        ),
    ]
