# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0040_astro_observatories_western_australia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_astronomy_ads',
            field=models.BooleanField(
                default=True,
                help_text='It would mean a lot if you chose to allow astronomy relevant, non intrusive ads on '
                          'this website. AstroBin is a small business run by a single person, and this kind of support '
                          'would be amazing. Thank you in advance!',
                verbose_name='Allow astronomy ads from our partners'),
        )
    ]
