# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 19:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import astrobin.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0042_add_uncompressed_source_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('zip_file',
                 models.FileField(max_length=256, null=True, upload_to=astrobin.models.data_download_upload_path)),
                ('file_size', models.IntegerField(null=True)),
                ('status', models.CharField(
                    choices=[(b'PENDING', 'Pending'), (b'PROCESSING', 'Processing'), (b'READY', 'Ready'),
                             (b'ERROR', 'Error'), (b'Expired', 'Expired')], default=b'PENDING', max_length=20)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
