# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0043_add_data_download_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadownloadrequest',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='datadownloadrequest',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datadownloadrequest',
            name='status',
            field=models.CharField(choices=[(b'PENDING', 'Pending'), (b'PROCESSING', 'Processing'), (b'READY', 'Ready'),
                                            (b'ERROR', 'Error'), (b'EXPIRED', 'Expired')], default=b'PENDING',
                                   max_length=20),
        ),
    ]
