# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0045_update_image_uncompressed_source_file_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[(b'CLEAR_OR_COLOR', 'Clear or color'), (b'BROAD HA', 'Broadband: H-Alpha'),
                                            (b'BROAD HB', 'Broadband: H-Beta'), (b'BROAD SII', 'Broadband: S-II'),
                                            (b'BROAD OIII', 'Broadband: O-III'), (b'BROAD NII', 'Broadband: N-II'),
                                            (b'NARROW HA', 'Narrowband: H-Alpha'), (b'NARROW HB', 'Narrowband: H-Beta'),
                                            (b'NARROW SII', 'Narrowband: S-II'), (b'NARROW OIII', 'Narrowband: O-III'),
                                            (b'NARROW NII', 'Narrowband: N-II'), (b'LP', 'Light pollution suppression'),
                                            (b'PLANETARY', 'Planetary'), (b'UHC', 'UHC: Ultra High Contrast'),
                                            (b'OTHER', 'Other')], max_length=64, null=True, verbose_name='Type'),
        )
    ]
