# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 21:39


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0045_update_image_uncompressed_source_file_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[('CLEAR_OR_COLOR', 'Clear or color'), ('BROAD HA', 'Broadband: H-Alpha'),
                                            ('BROAD HB', 'Broadband: H-Beta'), ('BROAD SII', 'Broadband: S-II'),
                                            ('BROAD OIII', 'Broadband: O-III'), ('BROAD NII', 'Broadband: N-II'),
                                            ('NARROW HA', 'Narrowband: H-Alpha'), ('NARROW HB', 'Narrowband: H-Beta'),
                                            ('NARROW SII', 'Narrowband: S-II'), ('NARROW OIII', 'Narrowband: O-III'),
                                            ('NARROW NII', 'Narrowband: N-II'), ('LP', 'Light pollution suppression'),
                                            ('PLANETARY', 'Planetary'), ('UHC', 'UHC: Ultra High Contrast'),
                                            ('OTHER', 'Other')], max_length=64, null=True, verbose_name='Type'),
        )
    ]
