# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0047_update_square_cropping_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerevision',
            name='skip_notifications',
            field=models.NullBooleanField(default=None, help_text='Do not notify your followers about this revision.',
                                          verbose_name='Skip notifications'),
        )
    ]
