# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0048_update_imagerevision_skip_notifications_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[(b'OPEN_SOURCE_OR_FREEWARE', 'Open source or freeware'), (b'PAID', 'Paid')],
                                   max_length=64, null=True, verbose_name='Type'),
        )
    ]
