# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0051_add_image_sharpen_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='solar_system_main_subject',
            field=models.CharField(blank=True,
                                   choices=[(b'SUN', 'Sun'), (b'MOON', "Earth's Moon"), (b'MERCURY', 'Mercury'),
                                            (b'VENUS', 'Venus'), (b'MARS', 'Mars'), (b'JUPITER', 'Jupiter'),
                                            (b'SATURN', 'Saturn'), (b'URANUS', 'Uranus'), (b'NEPTUNE', 'Neptune'),
                                            (b'MINOR_PLANET', 'Minor planet'), (b'COMET', 'Comet'),
                                            (b'OTHER', 'Other')],
                                   help_text='If the main subject of your image is a body in the solar system, please select which (or which type) it is.',
                                   max_length=16, null=True, verbose_name='Main solar system subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='subject_type',
            field=models.CharField(choices=[(None, b'---------'), (b'DEEP_SKY', 'Deep sky object or field'),
                                            (b'SOLAR_SYSTEM', 'Solar system body or event'),
                                            (b'WIDE_FIELD', 'Extremely wide field'), (b'STAR_TRALS', 'Star trails'),
                                            (b'NORTHERN_LIGHTS', 'Northern lights'), (b'GEAR', 'Gear'),
                                            (b'OTHER', 'Other')], max_length=16, verbose_name='Subject type'),
        ),
    ]
