# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 09:19


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0051_add_image_sharpen_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='solar_system_main_subject',
            field=models.CharField(blank=True,
                                   choices=[('SUN', 'Sun'), ('MOON', "Earth's Moon"), ('MERCURY', 'Mercury'),
                                            ('VENUS', 'Venus'), ('MARS', 'Mars'), ('JUPITER', 'Jupiter'),
                                            ('SATURN', 'Saturn'), ('URANUS', 'Uranus'), ('NEPTUNE', 'Neptune'),
                                            ('MINOR_PLANET', 'Minor planet'), ('COMET', 'Comet'),
                                            ('OTHER', 'Other')],
                                   help_text='If the main subject of your image is a body in the solar system, please select which (or which type) it is.',
                                   max_length=16, null=True, verbose_name='Main solar system subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='subject_type',
            field=models.CharField(choices=[(None, '---------'), ('DEEP_SKY', 'Deep sky object or field'),
                                            ('SOLAR_SYSTEM', 'Solar system body or event'),
                                            ('WIDE_FIELD', 'Extremely wide field'), ('STAR_TRALS', 'Star trails'),
                                            ('NORTHERN_LIGHTS', 'Northern lights'), ('GEAR', 'Gear'),
                                            ('OTHER', 'Other')], max_length=16, verbose_name='Subject type'),
        ),
    ]
