# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models

from astrobin.enums import SubjectType, SolarSystemSubject
from astrobin.models import Image

SUBJECT_TYPE_MIGRATION_MAP = {
    0: SubjectType.OTHER,
    100: SubjectType.DEEP_SKY,
    200: SubjectType.SOLAR_SYSTEM,
    300: SubjectType.WIDE_FIELD,
    400: SubjectType.STAR_TRAILS,
    450: SubjectType.NORTHERN_LIGHTS,
    500: SubjectType.GEAR,
    600: SubjectType.OTHER,
}  # type: Dict[int, str]

SOLAR_SYSTEM_SUBJECT_MIGRATION_MAP = {
    0: SolarSystemSubject.SUN,
    1: SolarSystemSubject.MOON,
    2: SolarSystemSubject.MERCURY,
    3: SolarSystemSubject.VENUS,
    4: SolarSystemSubject.MARS,
    5: SolarSystemSubject.JUPITER,
    6: SolarSystemSubject.SATURN,
    7: SolarSystemSubject.URANUS,
    8: SolarSystemSubject.NEPTUNE,
    9: SolarSystemSubject.MINOR_PLANET,
    10: SolarSystemSubject.COMET,
    11: SolarSystemSubject.OTHER,
}  # type: Dict[int, str]


def getImages(apps):
    return apps.get_model('astrobin', 'Image').objects.all()


def migrateSubjectTypeValues(apps, schema_editor):
    for i in getImages(apps):  # type: Image
        i.subject_type = SUBJECT_TYPE_MIGRATION_MAP[int(i.subject_type)]
        i.save()


def reverseMigrateSubjectTypeValues(apps, schema_editor):
    for i in getImages(apps).exclude(subject_type=None):  # type: Image
        i.subject_type = {v: k for k, v in SUBJECT_TYPE_MIGRATION_MAP.iteritems()}[i.subject_type]
        i.save()


def migrateSolarSystemSubjectValues(apps, schema_editor):
    for i in getImages(apps).exclude(solar_system_main_subject=None):  # type: Image
        i.solar_system_main_subject = SOLAR_SYSTEM_SUBJECT_MIGRATION_MAP[int(i.solar_system_main_subject)]
        i.save()


def reverseMigrateSolarSystemSubjectValues(apps, schema_editor):
    for i in getImages(apps).exclude(solar_system_main_subject=None):  # type: Image
        i.solar_system_main_subject = {v: k for k, v in SOLAR_SYSTEM_SUBJECT_MIGRATION_MAP.iteritems()}[
            i.solar_system_main_subject]
        i.save()


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0052_data_migrate_subject_type_and_solar_system_subject_to_charfield'),
    ]

    operations = [
        migrations.RunPython(migrateSubjectTypeValues, reverseMigrateSubjectTypeValues),
        migrations.RunPython(migrateSolarSystemSubjectValues, reverseMigrateSolarSystemSubjectValues),
    ]
