# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0065_add_skygems'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='never_activated_account_reminder_sent',
            field=models.DateTimeField(null=True),
        )
    ]
