# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-05 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0068_add_support_for_equipment_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
