# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0070_add_option_to_allow_retailer_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='equipment_item_listings',
            field=models.ManyToManyField(editable=False, related_name='gear_items', to='astrobin_apps_equipment.EquipmentItemListing'),
        ),
    ]
