# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0072_add_userprofile_recovered_images_notice_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='remote_source',
            field=models.CharField(blank=True,
                                   choices=[(None, b'---------'), (b'OWN', 'Non-commercial independent facility'),
                                            (None, b'---------'), (b'AC', b'AstroCamp'),
                                            (b'AHK', b'Astro Hostel Krasnodar'),
                                            (b'AOWA', b'Astro Observatories Western Australia'), (b'CS', b'ChileScope'),
                                            (b'DSNM', b'Dark Sky New Mexico'), (b'DSP', b'Dark Sky Portal'),
                                            (b'DSC', b'DeepSkyChile'), (b'DSW', b'DeepSkyWest'),
                                            (b'eEyE', b'e-EyE Extremadura'), (b'EITS', b'Eye In The Sky'),
                                            (b'GFA', b'Goldfield Astronomical Observatory'),
                                            (b'GMO', b'Grand Mesa Observatory'),
                                            (b'HMO', b"Heaven's Mirror Observatory"),
                                            (b'IC', b'IC Astronomy Observatories'), (b'ITU', b'Image The Universe'),
                                            (b'INS', b'Insight Observatory'), (b'iT', b'iTelescope'),
                                            (b'LGO', b'Lijiang Gemini Observatory'),
                                            (b'MARIO', b'Marathon Remote Imaging Observatory (MaRIO)'),
                                            (b'NMS', b'New Mexico Skies'), (b'OES', b'Observatorio El Sauce'),
                                            (b'PSA', b'PixelSkies'), (b'REM', b'RemoteSkies.net'),
                                            (b'REMSG', b'Remote Skygems'), (b'RLD', b'Riverland Dingo Observatory'),
                                            (b'ROBO', b'RoboScopes'), (b'SS', b'Sahara Sky'),
                                            (b'SPVO', b'San Pedro Valley Observatory'),
                                            (b'SRO', b'Sierra Remote Observatories'),
                                            (b'SRO2', b'Sky Ranch Observatory'), (b'SPOO', b'SkyPi Remote Observatory'),
                                            (b'SLO', b'Slooh'), (b'SSLLC', b'Stellar Skies LLC'),
                                            (b'OTHER', 'None of the above')],
                                   help_text='Which remote hosting facility did you use to acquire data for this image?',
                                   max_length=8, null=True, verbose_name='Remote data source'),
        ),
    ]
