# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0073_rename_skypi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_recovery_process_completed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_recovery_process_started',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
