# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 17:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0074_add_userprofile_flags_for_image_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delete_reason',
            field=models.CharField(blank=True, choices=[('NOT_ACTIVE', 'I am no longer active in astrophotography'), ('DID_NOT_MEET_EXPECTATIONS', 'This website did not meet my expectations'), ('DOESNT_WORK', "Something on this website doesn't work for me"), ('TOO_EXPENSIVE', 'The paid subscriptions are too expensive'), ('PREFER_NOT_TO_SAY', 'I prefer not to say'), ('OTHER', 'Other')], help_text='Why are you deleting your AstroBin account?', max_length=32, null=True, verbose_name='Delete reason'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delete_reason_other',
            field=models.CharField(blank=True, help_text='Please tell us why you are deleting your account (minimum 30 characters). Thanks!', max_length=512, null=True, verbose_name='Other'),
        ),
    ]
