# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0077_rename_astrobin_index_to_image_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='recovery_ignored',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
