# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0079_add_recovery_ignored_to_image_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploader_expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader_metadata',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader_name',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader_offset',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader_temporary_file_path',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader_upload_length',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
