# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0082_plate_solution_overlay_on_full_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='astrobin_index_bonus',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
