# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 09:19
from __future__ import unicode_literals

from django.db import migrations

from astrobin.enums import SubjectType

TYPO = "STAR_TRALS"

TYPO_MIGRATION_MAP = {
    TYPO: SubjectType.STAR_TRAILS,
}  # type: Dict[str, str]


def get_images(apps):
    # type: (object) -> QuerySet
    return apps.get_model('astrobin', 'Image').objects.all()


def migrate_typo_values(apps, schema_editor):
    get_images(apps).filter(subject_type=TYPO).update(subject_type=SubjectType.STAR_TRAILS)


def reverse_migrate_subject_type_values(apps, schema_editor):
    get_images(apps).filter(subject_type=SubjectType.STAR_TRAILS).update(subject_type=TYPO)


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0083_add_astrobin_index_bonus'),
    ]

    operations = [
        migrations.RunPython(migrate_typo_values, reverse_migrate_subject_type_values),
    ]
