# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 08:03


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0084_migrate_STAR_TRALS_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='solar_system_main_subject',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SUN', 'Sun'),
                    ('MOON', "Earth's Moon"),
                    ('MERCURY', 'Mercury'),
                    ('VENUS', 'Venus'),
                    ('MARS', 'Mars'),
                    ('JUPITER', 'Jupiter'),
                    ('SATURN', 'Saturn'),
                    ('URANUS', 'Uranus'),
                    ('NEPTUNE', 'Neptune'),
                    ('MINOR_PLANET', 'Minor planet'),
                    ('COMET', 'Comet'),
                    ('OCCULTATION', 'Occultation'),
                    ('CONJUNCTION', 'Conjunction'),
                    ('PARTIAL_LUNAR_ECLIPSE', 'Partial lunar eclipse'),
                    ('TOTAL_LUNAR_ECLIPSE', 'Total lunar eclipse'),
                    ('PARTIAL_SOLAR_ECLIPSE', 'Partial solar eclipse'),
                    ('ANULAR_SOLAR_ECLIPSE', 'Anular solar eclipse'),
                    ('TOTAL_SOLAR_ECLIPSE', 'Total solar eclipse'),
                    ('OTHER', 'Other')],
                help_text='If the main subject of your image is a body in the solar system, please select which (or which type) it is.',
                max_length=32,
                null=True,
                verbose_name='Main solar system subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='subject_type',
            field=models.CharField(
                choices=[
                    (None, '---------'),
                    ('DEEP_SKY', 'Deep sky object or field'),
                    ('SOLAR_SYSTEM', 'Solar system body or event'),
                    ('WIDE_FIELD', 'Extremely wide field'),
                    ('STAR_TRAILS', 'Star trails'),
                    ('NORTHERN_LIGHTS', 'Northern lights'),
                    ('GEAR', 'Gear'),
                    ('OTHER', 'Other')
                ],
                max_length=16,
                verbose_name='Subject type'),
        ),
    ]
