# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0088_rename_traditional_acquisition_type_to_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='designated_iotd_submitters',
            field=models.ManyToManyField(editable=False, related_name='designated_images_as_submitter',
                                         to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='image',
            name='designated_iotd_reviewers',
            field=models.ManyToManyField(editable=False, related_name='designated_images_as_reviewer',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
