# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-04 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0091_various'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seen_email_permissions',
        ),
    ]
