# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0092_remove_userprofile_seen_email_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploader_metadata',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='imagerevision',
            name='uploader_metadata',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
