# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0093_convert_uploader_metadata_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploader_in_progress',
            field=models.NullBooleanField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='uploader_in_progress',
            field=models.NullBooleanField(default=None, editable=False),
        ),
    ]
