# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0094_add_uploader_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_notifications_in_new_tab',
            field=models.NullBooleanField(),
        ),
    ]
