# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0099_add_telescope_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='license',
            field=models.CharField(
                choices=[
                    (b'ALL_RIGHTS_RESERVED', 'None (All rights reserved)'),
                    (b'ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE', 'Attribution-NonCommercial-ShareAlike Creative Commons'),
                    (b'ATTRIBUTION_NON_COMMERCIAL', 'Attribution-NonCommercial Creative Commons'),
                    (b'ATTRIBUTION_NON_COMMERCIAL_NO_DERIVS', 'Attribution-NonCommercial-NoDerivs Creative Commons'),
                    (b'ATTRIBUTION', 'Attribution Creative Commons'),
                    (b'ATTRIBUTION_SHARE_ALIKE', 'Attribution-ShareAlike Creative Commons'),
                    (b'ATTRIBUTION_NO_DERIVS', 'Attribution-NoDerivs Creative Commons')
                ],
                default=b'ALL_RIGHTS_RESERVED',
                max_length=40,
                verbose_name='License'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_license',
            field=models.CharField(
                choices=[
                    (b'ALL_RIGHTS_RESERVED', 'None (All rights reserved)'),
                    (b'ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE', 'Attribution-NonCommercial-ShareAlike Creative Commons'),
                    (b'ATTRIBUTION_NON_COMMERCIAL', 'Attribution-NonCommercial Creative Commons'),
                    (b'ATTRIBUTION_NON_COMMERCIAL_NO_DERIVS', 'Attribution-NonCommercial-NoDerivs Creative Commons'),
                    (b'ATTRIBUTION', 'Attribution Creative Commons'),
                    (b'ATTRIBUTION_SHARE_ALIKE', 'Attribution-ShareAlike Creative Commons'),
                    (b'ATTRIBUTION_NO_DERIVS', 'Attribution-NoDerivs Creative Commons')],
                default=b'ALL_RIGHTS_RESERVED',
                help_text='The license you select here is automatically applied to all your new images.',
                max_length=40,
                verbose_name='Default license'
            ),
        )
    ]
