# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0103_rename_default_gallery_sorting_upload_time_to_publication_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_member_since',
            field=models.BooleanField(
                default=True,
                verbose_name='Allow others to see when you created your AstroBin account',
            )
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_last_seen',
            field=models.BooleanField(
                default=True,
                verbose_name='Allow others to see when you last visited AstroBin',
            )
        ),
    ]
