# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0104_add_userprofile_display_member_since_and_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_in_country',
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
    ]
