# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0105_add_last_seen_in_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='full_size_display_limitation',
            field=models.CharField(
                blank=True, choices=[
                    (b'EVERYBODY', 'Everybody'),
                    (b'PAYING', 'Paying members only'),
                    (b'MEMBERS', 'Members only'),
                    (b'ME', 'Me only'),
                    (b'NOBODY', 'Nobody')
                ],
                default=b'EVERYBODY',
                help_text='Specify what user groups are allowed to view this image at its full size.',
                max_length=16,
                null=True,
                verbose_name='Allow full-size display'
            ),
        ),
    ]
