# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('astrobin', '0106_add_image_full_size_display_limitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_flag',
            field=models.CharField(blank=True, choices=[(b'WRONG_TYPE', b'This item is the wrong time'), (b'MULTIPLE_ITEMS', b'This item collates multiple objects'), (b'DIY', b'This item is a DIY object'), (b'MIGRATE', b'This item is ready for migration')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
