# Generated by Django 2.2.24 on 2021-07-06 09:53

import astrobin.fields
import common.upload_paths
import common.utils
import common.validators.file_validator
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0106_add_image_full_size_display_limitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='app',
            name='key',
            field=models.CharField(blank=True, default='', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='app',
            name='registrar',
            field=models.ForeignKey(editable=False, on_delete=models.SET(common.utils.get_sentinel_user), related_name='app_api_key', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='app',
            name='secret',
            field=models.CharField(blank=True, default='', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(blank=True, choices=[('CCD', 'CCD'), ('DSLR', 'DSLR'), ('GUIDER/PLANETARY', 'Guider/Planetary'), ('FILM', 'Film'), ('COMPACT', 'Compact'), ('VIDEO', 'Video camera')], max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='datadownloadrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='binning',
            field=models.IntegerField(blank=True, choices=[(1, '1x1'), (2, '2x2'), (3, '3x3'), (4, '4x4')], default=0, null=True, verbose_name='Binning'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(blank=True, choices=[('CLEAR_OR_COLOR', 'Clear or color'), ('BROAD HA', 'Broadband: H-Alpha'), ('BROAD HB', 'Broadband: H-Beta'), ('BROAD SII', 'Broadband: S-II'), ('BROAD OIII', 'Broadband: O-III'), ('BROAD NII', 'Broadband: N-II'), ('NARROW HA', 'Narrowband: H-Alpha'), ('NARROW HB', 'Narrowband: H-Beta'), ('NARROW SII', 'Narrowband: S-II'), ('NARROW OIII', 'Narrowband: O-III'), ('NARROW NII', 'Narrowband: N-II'), ('LP', 'Light pollution suppression'), ('PLANETARY', 'Planetary'), ('UHC', 'UHC: Ultra High Contrast'), ('OTHER', 'Other')], max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='astrobin.Gear'),
        ),
        migrations.AlterField(
            model_name='gearmakeautorename',
            name='rename_from',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Rename form'),
        ),
        migrations.AlterField(
            model_name='gearmakeautorename',
            name='rename_to',
            field=models.CharField(max_length=128, verbose_name='Rename to'),
        ),
        migrations.AlterField(
            model_name='image',
            name='acquisition_type',
            field=models.CharField(choices=[('REGULAR', 'Regular (e.g. medium/long exposure with a CCD or DSLR)'), ('EAA', 'Electronically-Assisted Astronomy (EAA, e.g. based on a live video feed)'), ('LUCKY', 'Lucky imaging'), ('DRAWING', 'Drawing/Sketch'), ('OTHER', 'Other/Unknown')], default='REGULAR', max_length=32, verbose_name='Acquisition type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='data_source',
            field=models.CharField(choices=[(None, '---------'), ('Self acquired', (('BACKYARD', 'Backyard'), ('TRAVELLER', 'Traveller'), ('OWN_REMOTE', 'Own remote observatory'))), ('Downloaded', (('AMATEUR_HOSTING', 'Amateur hosting facility'), ('PUBLIC_AMATEUR_DATA', 'Public amateur data'), ('PRO_DATA', 'Professional, scientific grade data'))), ('Other', (('MIX', 'Mix of multiple sources'), ('OTHER', 'None of the above'), ('UNKNOWN', 'Unknown')))], help_text='Where does the data for this image come from?', max_length=32, verbose_name='Data source'),
        ),
        migrations.AlterField(
            model_name='image',
            name='full_size_display_limitation',
            field=models.CharField(blank=True, choices=[('EVERYBODY', 'Everybody'), ('PAYING', 'Paying members only'), ('MEMBERS', 'Members only'), ('ME', 'Me only'), ('NOBODY', 'Nobody')], default='EVERYBODY', help_text='Specify what user groups are allowed to view this image at its full size.', max_length=16, null=True, verbose_name='Allow full-size display'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='h', max_length=256, null=True, upload_to=common.upload_paths.image_upload_path, width_field='w'),
        ),
        migrations.AlterField(
            model_name='image',
            name='license',
            field=models.CharField(choices=[('ALL_RIGHTS_RESERVED', 'None (All rights reserved)'), ('ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE', 'Attribution-NonCommercial-ShareAlike Creative Commons'), ('ATTRIBUTION_NON_COMMERCIAL', 'Attribution-NonCommercial Creative Commons'), ('ATTRIBUTION_NON_COMMERCIAL_NO_DERIVS', 'Attribution-NonCommercial-NoDerivs Creative Commons'), ('ATTRIBUTION', 'Attribution Creative Commons'), ('ATTRIBUTION_SHARE_ALIKE', 'Attribution-ShareAlike Creative Commons'), ('ATTRIBUTION_NO_DERIVS', 'Attribution-NoDerivs Creative Commons')], default='ALL_RIGHTS_RESERVED', max_length=40, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='image',
            name='mouse_hover_image',
            field=models.CharField(blank=True, default='SOLUTION', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='remote_source',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('OWN', 'Non-commercial independent facility'), (None, '---------'), ('AC', 'AstroCamp'), ('AHK', 'Astro Hostel Krasnodar'), ('AOWA', 'Astro Observatories Western Australia'), ('CS', 'ChileScope'), ('DSNM', 'Dark Sky New Mexico'), ('DSP', 'Dark Sky Portal'), ('DSC', 'DeepSkyChile'), ('DSW', 'DeepSkyWest'), ('eEyE', 'e-EyE Extremadura'), ('EITS', 'Eye In The Sky'), ('GFA', 'Goldfield Astronomical Observatory'), ('GMO', 'Grand Mesa Observatory'), ('HMO', "Heaven's Mirror Observatory"), ('IC', 'IC Astronomy Observatories'), ('ITU', 'Image The Universe'), ('INS', 'Insight Observatory'), ('iT', 'iTelescope'), ('LGO', 'Lijiang Gemini Observatory'), ('MARIO', 'Marathon Remote Imaging Observatory (MaRIO)'), ('NMS', 'New Mexico Skies'), ('OES', 'Observatorio El Sauce'), ('PSA', 'PixelSkies'), ('REM', 'RemoteSkies.net'), ('REMSG', 'Remote Skygems'), ('RLD', 'Riverland Dingo Observatory'), ('ROBO', 'RoboScopes'), ('SS', 'Sahara Sky'), ('SPVO', 'San Pedro Valley Observatory'), ('SRO', 'Sierra Remote Observatories'), ('SRO2', 'Sky Ranch Observatory'), ('SPOO', 'SkyPi Remote Observatory'), ('SLO', 'Slooh'), ('SSLLC', 'Stellar Skies LLC'), ('TELI', 'Telescope Live'), ('OTHER', 'None of the above')], help_text='Which remote hosting facility did you use to acquire data for this image?', max_length=8, null=True, verbose_name='Remote data source'),
        ),
        migrations.AlterField(
            model_name='image',
            name='solar_system_main_subject',
            field=models.CharField(blank=True, choices=[('SUN', 'Sun'), ('MOON', "Earth's Moon"), ('MERCURY', 'Mercury'), ('VENUS', 'Venus'), ('MARS', 'Mars'), ('JUPITER', 'Jupiter'), ('SATURN', 'Saturn'), ('URANUS', 'Uranus'), ('NEPTUNE', 'Neptune'), ('MINOR_PLANET', 'Minor planet'), ('COMET', 'Comet'), ('OCCULTATION', 'Occultation'), ('CONJUNCTION', 'Conjunction'), ('PARTIAL_LUNAR_ECLIPSE', 'Partial lunar eclipse'), ('TOTAL_LUNAR_ECLIPSE', 'Total lunar eclipse'), ('PARTIAL_SOLAR_ECLIPSE', 'Partial solar eclipse'), ('ANULAR_SOLAR_ECLIPSE', 'Anular solar eclipse'), ('TOTAL_SOLAR_ECLIPSE', 'Total solar eclipse'), ('OTHER', 'Other')], help_text='If the main subject of your image is a body in the solar system, please select which (or which type) it is.', max_length=32, null=True, verbose_name='Main solar system subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='subject_type',
            field=models.CharField(choices=[(None, '---------'), ('DEEP_SKY', 'Deep sky object or field'), ('SOLAR_SYSTEM', 'Solar system body or event'), ('WIDE_FIELD', 'Extremely wide field'), ('STAR_TRAILS', 'Star trails'), ('NORTHERN_LIGHTS', 'Northern lights'), ('GEAR', 'Gear'), ('OTHER', 'Other')], max_length=16, verbose_name='Subject type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uncompressed_source_file',
            field=models.FileField(help_text='You can store the final processed image that came out of your favorite image editor (e.g. PixInsight, Adobe Photoshop, etc) here on AstroBin, for archival purposes. This file is stored privately and only you will have access to it.', max_length=256, null=True, upload_to=common.upload_paths.uncompressed_source_upload_path, validators=[common.validators.file_validator.FileValidator(allowed_extensions=('xisf', 'fits', 'fit', 'fts', 'psd', 'tif', 'tiff'))], verbose_name='Uncompressed source (max 100 MB)'),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermark_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', help_text='The final font size will depend on how long your watermark is.', max_length=1, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='imagerequest',
            name='type',
            field=models.CharField(choices=[('INFO', 'Additional information'), ('FITS', 'TIFF/FITS'), ('HIRES', 'Higher resolution')], max_length=8),
        ),
        migrations.AlterField(
            model_name='imagerevision',
            name='image_file',
            field=models.ImageField(height_field='h', max_length=256, null=True, upload_to=common.upload_paths.image_upload_path, width_field='w'),
        ),
        migrations.AlterField(
            model_name='imagerevision',
            name='mouse_hover_image',
            field=models.CharField(blank=True, default='SOLUTION', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=astrobin.fields.CountryField(blank=True, choices=[('', '---------'), ('GB', 'United Kingdom'), ('AF', 'Afghanistan'), ('AX', 'Aland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', 'Cape Verde'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo, The Democratic Republic of the'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Cote d'Ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See (Vatican City State)'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran, Islamic Republic of'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KP', "Korea, Democratic People's Republic of"), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libyan Arab Jamahiriya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MK', 'Macedonia, The Former Yugoslav Republic of'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia, Federated States of'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('AN', 'Netherlands Antilles'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestinian Territory, Occupied'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Reunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('BL', 'Saint Barthelemy'), ('SH', 'Saint Helena'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SZ', 'Swaziland'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania, United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Viet Nam'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat_side',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South')], default='N', max_length=1, verbose_name='North or south'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon_side',
            field=models.CharField(choices=[('E', 'East'), ('W', 'West')], default='E', max_length=1, verbose_name='East or West'),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(blank=True, choices=[('OPEN_SOURCE_OR_FREEWARE', 'Open source or freeware'), ('PAID', 'Paid')], max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='type',
            field=models.CharField(blank=True, choices=[('REFR ACHRO', 'Refractor: achromatic'), ('REFR SEMI-APO', 'Refractor: semi-apochromatic'), ('REFR APO', 'Refractor: apochromatic'), ('REFR NON-ACHRO GALILEAN', 'Refractor: non-achromatic Galilean'), ('REFR NON-ACHRO KEPLERIAN', 'Refractor: non-achromatic Keplerian'), ('REFR SUPERACHRO', 'Refractor: superachromat'), ('REFL DALL-KIRKHAM', 'Reflector: Dall-Kirkham'), ('REFL NASMYTH', 'Reflector: Nasmyth'), ('REFL RITCHEY CHRETIEN', 'Reflector: Ritchey Chretien'), ('REFL GREGORIAN', 'Reflector: Gregorian'), ('REFL HERSCHELLIAN', 'Reflector: Herschellian'), ('REFL NEWTONIAN', 'Reflector: Newtonian'), ('CATA ARGUNOV-CASSEGRAIN', 'Catadioptric: Argunov-Cassegrain'), ('CATA KLEVTSOV-CASSEGRAIN', 'Catadioptric: Klevtsov-Cassegrain'), ('CATA LURIE-HOUGHTON', 'Catadioptric: Lurie-Houghton'), ('CATA MAKSUTOV', 'Catadioptric: Maksutov'), ('CATA MAKSUTOV-CASSEGRAIN', 'Catadioptric: Maksutov-Cassegrain'), ('CATA MOD DALL-KIRKHAM', 'Catadioptric: modified Dall-Kirkham'), ('CATA SCHMIDT CAMERA', 'Catadioptric: Schmidt camera'), ('CATA SCHMIDT-CASSEGRAIN', 'Catadioptric: Schmidt-Cassegrain'), ('CATA ACF SCHMIDT-CASSEGRAIN', 'Catadioptric: ACF Schmidt-Cassegrain'), ('CATA ROWE-ACKERMANN SCHMIDT', 'Catadioptric: Rowe-Atkinson Schmidt astrograph'), ('CAMERA LENS', 'Camera lens'), ('BINOCULARS', 'Binoculars')], max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_frontpage_section',
            field=models.CharField(choices=[('global', 'Global stream'), ('personal', 'Personal stream'), ('recent', 'All uploaded images'), ('followed', 'All images uploaded by people you follow')], default='global', max_length=16, verbose_name='Default front page view'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_license',
            field=models.CharField(choices=[('ALL_RIGHTS_RESERVED', 'None (All rights reserved)'), ('ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE', 'Attribution-NonCommercial-ShareAlike Creative Commons'), ('ATTRIBUTION_NON_COMMERCIAL', 'Attribution-NonCommercial Creative Commons'), ('ATTRIBUTION_NON_COMMERCIAL_NO_DERIVS', 'Attribution-NonCommercial-NoDerivs Creative Commons'), ('ATTRIBUTION', 'Attribution Creative Commons'), ('ATTRIBUTION_SHARE_ALIKE', 'Attribution-ShareAlike Creative Commons'), ('ATTRIBUTION_NO_DERIVS', 'Attribution-NoDerivs Creative Commons')], default='ALL_RIGHTS_RESERVED', help_text='The license you select here is automatically applied to all your new images.', max_length=40, verbose_name='Default license'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_watermark_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='delete_reason',
            field=models.CharField(choices=[('NOT_ACTIVE', 'I am no longer active in astrophotography'), ('DID_NOT_MEET_EXPECTATIONS', 'This website did not meet my expectations'), ('DOESNT_WORK', "Something on this website doesn't work for me"), ('TOO_EXPENSIVE', 'The paid subscriptions are too expensive'), ('PREFER_NOT_TO_SAY', 'I prefer not to say'), ('OTHER', 'Other')], help_text='Why are you deleting your AstroBin account?', max_length=32, null=True, verbose_name='Delete reason'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_username',
            field=models.CharField(blank=True, help_text="If you provide this, AstroBin will tag you on Instagram if it's sharing an image of yours.", max_length=31, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(31), django.core.validators.RegexValidator('^@[\\w](?!.*?\\.{2})[\\w.]{1,28}[\\w]$', 'An Instagram username must be between 3 and 30 characters, start with an @ sign, and only have letters, numbers, periods, and underlines.')], verbose_name='Instagram username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English (US)'), ('en-GB', 'English (GB)'), ('it', 'Italian'), ('es', 'Spanish'), ('fr', 'French'), ('fi', 'Finnish'), ('de', 'German'), ('nl', 'Dutch'), ('tr', 'Turkish'), ('sq', 'Albanian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('el', 'Greek'), ('ru', 'Russian'), ('ar', 'Arabic'), ('ja', 'Japanese')], max_length=8, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='open_notifications_in_new_tab',
            field=models.NullBooleanField(verbose_name='Open notifications in a new tab'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_signatures',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show signatures'),
        ),
    ]
