# Generated by Django 2.2.24 on 2021-07-15 11:52

import re

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0108_add_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description_bbcode',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
