# Generated by Django 2.2.24 on 2021-07-15 11:52
import re

from django.db import migrations, models
from html2bbcode.parser import HTML2BBCode


def image_description_html2bbcode(apps, schema_editor):
    Image = apps.get_model('astrobin', 'Image')

    for image in Image.objects.all().iterator():
        parser = HTML2BBCode('/opt/project/astrobin/html2bbcode.conf')

        description = image.description

        if description:
            description = re.sub(r'<br>', '\n', description)
            description = re.sub(r'<br/>', '\n', description)
            description = re.sub(r'\n+', '\n\n', description)

            description_bbcode = str(parser.feed(description))
            Image.objects.filter(pk=image.pk).update(description_bbcode=description_bbcode)


def revert_image_description_html2bbcode(apps, schema_editor):
    Image = apps.get_model('astrobin', 'Image')

    for image in Image.objects.all().iterator():
        Image.objects.filter(pk=image.pk).update(description_bbcode=None)


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0108_add_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description_bbcode',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.RunPython(image_description_html2bbcode, revert_image_description_html2bbcode)
    ]
