# Generated by Django 2.2.24 on 2021-07-13 19:04

import re
from django.db import migrations
from html2bbcode.parser import HTML2BBCode
from precise_bbcode.shortcuts import render_bbcodes


def image_description_html2bbcode(apps, schema_editor):
    Image = apps.get_model('astrobin', 'Image')

    for image in Image.objects.all().iterator():
        parser = HTML2BBCode('/opt/project/astrobin/html2bbcode.conf')

        description = image.description
        description = re.sub(r'<br>', '\n', description)
        description = re.sub(r'<br/>', '\n', description)
        description = re.sub(r'\n+', '\n\n', description)

        description_bbcode = str(parser.feed(description))
        Image.objects.filter(pk=image.pk).update(description=description_bbcode)


def image_description_bbcode2html(apps, schema_editor):
    Image = apps.get_model('astrobin', 'Image')

    for image in Image.objects.all().iterator():
        description_html = render_bbcodes(image.description)
        Image.objects.filter(pk=image.pk).update(description=description_html)


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0109_remove_help_text_from_image_description'),
    ]

    operations = [
        migrations.RunPython(image_description_html2bbcode, image_description_bbcode2html)
    ]
