# Generated by Django 2.2.24 on 2021-10-05 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0110_migrate_itelescope_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearassistedmerge',
            name='master',
        ),
        migrations.RemoveField(
            model_name='gearassistedmerge',
            name='slave',
        ),
        migrations.DeleteModel(
            name='GearHardMergeRedirect',
        ),
        migrations.DeleteModel(
            name='GearMakeAutoRename',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='moderator_fixed',
        ),
        migrations.DeleteModel(
            name='GearAssistedMerge',
        ),
    ]
