# Generated by Django 2.2.24 on 2021-10-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0111_remove_old_gear_merge_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileGearMergeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_gear_merge_records_as_from', to='astrobin.Gear')),
                ('to_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_gear_merge_records_as_to', to='astrobin.Gear')),
                ('user_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='gear_merge_records', to='astrobin.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGearMergeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image_gear_merge_records_as_from', to='astrobin.Gear')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='gear_merge_records', to='astrobin.Image')),
                ('to_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='image_gear_merge_records_as_to', to='astrobin.Gear')),
            ],
        ),
    ]
