# Generated by Django 2.2.24 on 2021-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0112_add_gear_merge_record_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearuserinfo',
            name='modded',
            field=models.NullBooleanField(help_text='Has this object been modified for astrophotography? (especially applicable to cameras)', verbose_name='Modded'),
        ),
    ]
