# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-23 19:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('astrobin', '0114_'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_flag',
            field=models.CharField(blank=True, choices=[
                ('WRONG_TYPE', 'This item is the wrong type'),
                ('MULTIPLE_ITEMS', 'This item collates multiple objects'),
                ('DIY', 'This item is a DIY object'),
                ('MIGRATE', 'This item is ready for migration')
            ], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
