# Generated by Django 2.2.24 on 2021-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0114_remove_word_time_from_publication_and_acquisition_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='download_limitation',
            field=models.CharField(blank=True, choices=[('EVERYBODY', 'Everybody'), ('ME', 'Me only')], default='ME',
                                   help_text='Please note: even if you allow everyone to access download options, only you will be able to download the originally uploaded file.',
                                   max_length=16, null=True, verbose_name='Display download menu'),
        ),
    ]
