# Generated by Django 2.2.24 on 2021-07-27 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0115_add_gear_migration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_flag_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_flag_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
