# Generated by Django 2.2.24 on 2021-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0116_add_gear_migration_flag_reviewer_rejection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_flag_reviewer_decision',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ACCEPTED', 'Accepted'),
                    ('REJECTED_INCORRECT_STRATEGY', 'Rejected: incorrect migration strategy'),
                    ('REJECTED_WRONG_MIGRATION_TARGET', 'Rejected: wrong migration target'),
                    ('REJECTED_BAD_MIGRATION_TARGET', 'Rejected: bad migration target'),
                    ('REJECTED_OTHER', 'Rejected: other')
                ],
                max_length=32,
                null=True),
        ),
    ]
