# Generated by Django 2.2.24 on 2021-08-24 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0116_add_gear_migration_flag_moderator_and_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_flag_moderator_lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='migrated_gear_item_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_flag_moderator_lock_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='migration_flag_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='migrated_gear_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
