# Generated by Django 2.2.24 on 2021-09-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0117_add_gear_migration_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='migration_flag',
            field=models.CharField(
                blank=True,
                choices=[
                    ('WRONG_TYPE', 'This item is the wrong type'),
                    ('MULTIPLE_ITEMS', 'This item collates multiple objects'),
                    ('DIY', 'This item is a DIY object'),
                    ('NOT_ENOUGH_INFO', 'This item does not have enough information to decide on a migration strategy'),
                    ('MIGRATE', 'This item is ready for migration')
                ],
                max_length=16,
                null=True),
        ),
    ]
