# Generated by Django 2.2.24 on 2021-08-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0117_add_gear_migration_moderation_lock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_flag_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='reviewed_for_migration_gear_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_flag_reviewer_lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='reviewed_for_migration_gear_item_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gear',
            name='migration_flag_reviewer_lock_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
