# Generated by Django 2.2.24 on 2021-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0118_add_NOT_ENOUGH_INFO_gear_migration_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='migration_flag_reviewer_rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
