# Generated by Django 2.2.24 on 2021-11-23 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0127_remove_model_global_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='migration_content_type',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_moderator',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_reviewer',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_reviewer_decision',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_reviewer_lock',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_reviewer_lock_timestamp',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_reviewer_rejection_comment',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_flag_timestamp',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='migration_object_id',
        ),
        migrations.CreateModel(
            name='GearMigrationStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_flag', models.CharField(choices=[('WRONG_TYPE', 'This item is the wrong type'), ('MULTIPLE_ITEMS', 'This item collates multiple objects'), ('DIY', 'This item is a DIY object'), ('NOT_ENOUGH_INFO', 'This item does not have enough information to decide on a migration strategy'), ('MIGRATE', 'This item is ready for migration')], max_length=16)),
                ('migration_flag_timestamp', models.DateTimeField(blank=True, null=True)),
                ('migration_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('migration_flag_reviewer_lock_timestamp', models.DateTimeField(blank=True, null=True)),
                ('migration_flag_reviewer_decision', models.CharField(blank=True, choices=[('APPROVED', 'Approved')], max_length=32, null=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_strategies', to='astrobin.Gear')),
                ('migration_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('migration_flag_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_gear_items', to=settings.AUTH_USER_MODEL)),
                ('migration_flag_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_for_migration_gear_items', to=settings.AUTH_USER_MODEL)),
                ('migration_flag_reviewer_lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_for_migration_gear_item_locks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear_migration_strateogies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gear', 'user')},
            },
        ),
    ]
