# Generated by Django 2.2.24 on 2021-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0040_add_field_group_to_equipment_items'),
        ('astrobin', '0128_add_model_gear_migration_strategy'),
    ]

    operations = [
        ################################################################################################################
        # NEW FIELDS
        ################################################################################################################
        migrations.AddField(
            model_name='image',
            name='accessories_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using',
                to='astrobin_apps_equipment.Accessory', verbose_name='Accessories'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='filters_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin_apps_equipment.Filter',
                verbose_name='Filters'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='guiding_cameras_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_guiding',
                to='astrobin_apps_equipment.Camera', verbose_name='Guiding cameras'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='guiding_telescopes_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_guiding',
                to='astrobin_apps_equipment.Telescope',
                verbose_name='Guiding telescopes or lenses'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='imaging_cameras_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_imaging',
                to='astrobin_apps_equipment.Camera', verbose_name='Imaging cameras'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='imaging_telescopes_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_imaging',
                to='astrobin_apps_equipment.Telescope',
                verbose_name='Imaging telescopes or lenses'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='mounts_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin_apps_equipment.Mount',
                verbose_name='Mounts'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='software_v2',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin_apps_equipment.Software',
                verbose_name='Software'
            ),
        ),

        ################################################################################################################
        # ALTER RELATED NAME ON LEGACY ITEMS FOR IMAGE
        ################################################################################################################
        migrations.AlterField(
            model_name='image',
            name='accessories',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin.Accessory',
                verbose_name='Accessories'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='filters',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin.Filter',
                verbose_name='Filters'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='focal_reducers',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin.FocalReducer',
                verbose_name='Focal reducers'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='guiding_cameras',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_guiding', to='astrobin.Camera',
                verbose_name='Guiding cameras'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='guiding_telescopes',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_guiding', to='astrobin.Telescope',
                verbose_name='Guiding telescopes or lenses'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='imaging_cameras',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_imaging', to='astrobin.Camera',
                verbose_name='Imaging cameras'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='imaging_telescopes',
            field=models.ManyToManyField(
                blank=True, related_name='images_using_for_imaging', to='astrobin.Telescope',
                verbose_name='Imaging telescopes or lenses'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='mounts',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin.Mount',
                verbose_name='Mounts'
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='software',
            field=models.ManyToManyField(
                blank=True, related_name='images_using', to='astrobin.Software',
                verbose_name='Software'
            ),
        ),

        ################################################################################################################
        # ALTER RELATED NAME ON LEGACY ITEMS FOR USERPROFILE
        ################################################################################################################
        migrations.AlterField(
            model_name='userprofile',
            name='accessories',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.Accessory',
                verbose_name='Accessories'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cameras',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.Camera',
                verbose_name='Cameras'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='filters',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.Filter',
                verbose_name='Filters'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='focal_reducers',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.FocalReducer',
                verbose_name='Focal reducers'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mounts',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.Mount',
                verbose_name='Mounts'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='software',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.Software',
                verbose_name='Software'
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telescopes',
            field=models.ManyToManyField(
                blank=True, related_name='users_using', to='astrobin.Telescope',
                verbose_name='Telescopes and lenses'
            ),
        ),
    ]
