# Generated by Django 2.2.24 on 2021-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0129_add_new_equipment_item_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='accessories_v2',
            new_name='accessories_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='filters_v2',
            new_name='filters_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='guiding_cameras_v2',
            new_name='guiding_cameras_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='guiding_telescopes_v2',
            new_name='guiding_telescopes_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imaging_cameras_v2',
            new_name='imaging_cameras_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imaging_telescopes_v2',
            new_name='imaging_telescopes_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='mounts_v2',
            new_name='mounts_2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='software_v2',
            new_name='software_2',
        ),
    ]
