# Generated by Django 2.2.24 on 2021-12-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0131_add_deepsky_villa_remote_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_submit_to_iotd_tp_process',
            field=models.BooleanField(
                default=False,
                help_text='Check this box to automatically submit your images for '
                          '<a href="https://welcome.astrobin.com/iotd" target="_blank">IOTD/TP</a> consideration '
                          'when they are published',
                verbose_name='Automatically submit images for IOTD/TP consideration'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seen_iotd_tp_is_explicit_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
