# Generated by Django 2.2.24 on 2022-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0133_add_subject_type_noctilucent_clouds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='solar_system_main_subject',
            field=models.CharField(blank=True,
                choices=[('SUN', 'Sun'), ('MOON', "Earth's Moon"), ('MERCURY', 'Mercury'), ('VENUS', 'Venus'),
                         ('MARS', 'Mars'), ('JUPITER', 'Jupiter'), ('SATURN', 'Saturn'), ('URANUS', 'Uranus'),
                         ('NEPTUNE', 'Neptune'), ('MINOR_PLANET', 'Minor planet'), ('COMET', 'Comet'),
                         ('OCCULTATION', 'Occultation'), ('CONJUNCTION', 'Conjunction'),
                         ('PARTIAL_LUNAR_ECLIPSE', 'Partial lunar eclipse'),
                         ('TOTAL_LUNAR_ECLIPSE', 'Total lunar eclipse'),
                         ('PARTIAL_SOLAR_ECLIPSE', 'Partial solar eclipse'),
                         ('ANULAR_SOLAR_ECLIPSE', 'Anular solar eclipse'),
                         ('TOTAL_SOLAR_ECLIPSE', 'Total solar eclipse'), ('METEOR_SHOWER', 'Meteor shower'),
                         ('OTHER', 'Other')],
                help_text='If the main subject of your image is a body in the solar system, please select which (or which type) it is.',
                max_length=32, null=True, verbose_name='Main solar system subject'
            ),
        ),
    ]
