# Generated by Django 2.2.24 on 2022-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0134_add_solar_system_main_subject_meteor_shower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_watermark',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_watermark_opacity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_watermark_position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_watermark_size',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_watermark_text',
        ),
    ]
