# Generated by Django 2.2.24 on 2022-02-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0137_add_west_texas_observatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem_acquisition',
            name='exposure_per_frame',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Exposure per frame (ms)'),
        ),
    ]
