# Generated by Django 2.2.24 on 2022-03-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0139_add_tai_yuge_observatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='bias',
            field=models.PositiveIntegerField(
                blank=True, help_text='The number of bias/offset frames.', null=True, verbose_name='Bias'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='bortle',
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, '1 - Excellent dark-site sky (BLACK)'), (2, '2 - Typical truly dark site (GRAY)'),
                         (3, '3 - Rural sky (BLUE)'), (4, '4 - Rural/suburban transition (GREEN/YELLOW)'),
                         (5, '5 - Suburban sky (ORANGE)'), (6, '6 - Bright suburban sky (RED)'),
                         (7, '7 - Suburban/urban transition or Full Moon (RED)'), (8, '8 - City sky (WHITE)'),
                         (9, '9 - Inner city sky (WHITE)')],
                help_text='Quality of the sky according to <a href="http://en.wikipedia.org/wiki/Bortle_Dark-Sky_Scale" target="_blank">the Bortle Scale</a>.',
                null=True, verbose_name='Bortle Dark-Sky Scale'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='darks',
            field=models.PositiveIntegerField(
                blank=True, help_text='The number of dark frames.', null=True, verbose_name='Darks'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='duration',
            field=models.PositiveIntegerField(
                blank=True, help_text='Duration of each sub-frame, in seconds.', null=True, verbose_name='Duration'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='filter',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='deep_sky_acquisitions', to='astrobin.Filter', verbose_name='Filter'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='flat_darks',
            field=models.PositiveIntegerField(
                blank=True, help_text='The number of dark flat frames.', null=True, verbose_name='Flat darks'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='flats',
            field=models.PositiveIntegerField(
                blank=True, help_text='The number of flat frames.', null=True, verbose_name='Flats'
            ),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='iso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO'),
        ),
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='number',
            field=models.PositiveIntegerField(
                blank=True, help_text='The number of sub-frames.', null=True, verbose_name='Number'
            ),
        ),
    ]
