# Generated by Django 2.2.24 on 2022-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0140_add_positive_number_constraints_to_some_acquisition_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deepsky_acquisition',
            options={'ordering': ['saved_on']},
        ),
        migrations.AddField(
            model_name='deepsky_acquisition',
            name='f_number',
            field=models.DecimalField(
                blank=True, decimal_places=2,
                help_text='If you used a camera lens, please specify the f-number (also known as f-ratio or f-stop) that you used for this acquisition session.',
                max_digits=4, null=True, verbose_name='f-number'
            ),
        ),
    ]
