# Generated by Django 2.2.24 on 2022-05-16 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0145_add_remote_source_hakos_astro_farm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageGearMergeRecord',
        ),
        migrations.DeleteModel(
            name='UserProfileGearMergeRecord',
        ),
    ]
