# Generated by Django 2.2.24 on 2022-05-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0146_delete_gear_merge_record_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepsky_acquisition',
            name='filter_2',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='deep_sky_acquisitions', to='astrobin_apps_equipment.Filter', verbose_name='Filter'
            ),
        ),
    ]
