# Generated by Django 2.2.24 on 2022-05-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0147_add_filter_2_to_deep_sky_acquisitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearmigrationstrategy',
            name='migration_flag',
            field=models.CharField(
                choices=[
                    ('WRONG_TYPE', 'This item is the wrong type'),
                    ('MULTIPLE_ITEMS', 'This item collates multiple objects'),
                    ('NOT_ENOUGH_INFO', 'This item does not have enough information to decide on a migration strategy'),
                    ('MIGRATE', 'This item is ready for migration')
                ],
                max_length=16
            ),
        ),
    ]
