# Generated by Django 2.2.24 on 2022-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0149_add_skiesaway_remote_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='submitted_for_iotd_tp_consideration',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
