# Generated by Django 2.2.24 on 2022-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0151_add_on_delete_to_app_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='secret',
            field=models.CharField(blank=True, default='', editable=False, max_length=256),
        ),
    ]
