# Generated by Django 2.2.24 on 2022-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0152_alter_app_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadownloadrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('READY', 'Ready'),
                    ('ERROR', 'Error'),
                    ('EXPIRED', 'Expired')
                ],
                default='PENDING',
                max_length=20
            ),
        ),
    ]
