# Generated by Django 2.2.24 on 2022-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0155_alter_imagerevision_mouse_hover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat_side',
            field=models.CharField(
                choices=[('N', 'North'), ('S', 'South')], default='N', max_length=1, verbose_name='North or south'
            ),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon_side',
            field=models.CharField(
                choices=[('E', 'East'), ('W', 'West')], default='E', max_length=1, verbose_name='East or West'
            ),
        ),
    ]
