# Generated by Django 2.2.24 on 2022-06-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0157_various_userprofile_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gearmigrationstrategy',
            options={'ordering': ('-pk',)},
        ),
    ]
