# Generated by Django 2.2.24 on 2022-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0158_add_ordering_to_gear_migration_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearmigrationstrategy',
            name='applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
