# Generated by Django 2.2.24 on 2022-08-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0161_increase_max_length_of_remote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='duration',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Duration of each sub-frame, in seconds.',
                max_digits=10,
                null=True,
                verbose_name='Duration'
            ),
        ),
    ]
