# Generated by Django 2.2.24 on 2022-08-30 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0162_make_deep_sky_acquisition_duration_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='images_as_collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
