# Generated by Django 2.2.24 on 2023-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0166_add_dark_matter_astrophotography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sharpen_thumbnails',
            field=models.BooleanField(default=False, help_text='If selected, AstroBin will use a resizing algorithm that slightly sharpens all sizes of the image except the full size version.', verbose_name='Sharpen thumbnails'),
        ),
    ]
