# Generated by Django 2.2.24 on 2023-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0167_fix_help_text_of_image_sharpen_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspended'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Suspension reason'),
        ),
    ]
