# Generated by Django 2.2.24 on 2023-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0168_add_userprofile_suspended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
