# Generated by Django 2.2.24 on 2023-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0171_add_iso_gain_to_ssa_and_fix_flat_darks_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_country',
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
    ]
