# Generated by Django 2.2.24 on 2023-07-19 11:24

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0174_add_alnitak_remote_observatories_remote_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='encoded_video_file',
            field=models.FileField(max_length=256, null=True, upload_to=common.upload_paths.video_upload_path),
        ),
        migrations.AddField(
            model_name='image',
            name='video_file',
            field=models.FileField(max_length=256, null=True, upload_to=common.upload_paths.video_upload_path),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='encoded_video_file',
            field=models.FileField(max_length=256, null=True, upload_to=common.upload_paths.video_upload_path),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='video_file',
            field=models.FileField(max_length=256, null=True, upload_to=common.upload_paths.video_upload_path),
        ),
    ]
