# Generated by Django 2.2.24 on 2023-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0174_add_alnitak_remote_observatories_remote_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='duration',
            field=models.DecimalField(
                blank=True, decimal_places=4, help_text='Duration of each sub-frame, in seconds.', max_digits=10,
                null=True, verbose_name='Duration'
            ),
        ),
    ]
