# Generated by Django 2.2.24 on 2023-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0176_add_video_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='loop_video',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='loop_video',
            field=models.NullBooleanField(default=None),
        ),
    ]
