# Generated by Django 2.2.24 on 2023-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin', '0177_add_loop_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='encoding_error',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='encoding_error',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
