# Generated by Django 2.2.24 on 2023-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0179_add_userprofile_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agreed_to_iotd_tp_rules_and_guidelines',
            field=models.DateTimeField(
                blank=True,
                help_text='Check this box to confirm that you have read and agree to the IOTD/TP <a href="https://welcome.astrobin.com/iotd#rules" target="_blank">rules</a> and <a href="https://welcome.astrobin.com/iotd#photographer-guidelines" target="_blank">guidelines</a>. Your images won\'t be submitted for IOTD/TP consideration if you don\'t agree.',
                null=True, verbose_name='I agree to the IOTD/TP rules and guidelines'
            ),
        ),
    ]
