# Generated by Django 2.2.24 on 2023-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0182_add_astronomy_acres_to_remote_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detected_insecure_password',
            field=models.DateTimeField(null=True),
        ),
    ]
