# Generated by Django 2.2.24 on 2023-11-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('astrobin', '0183_add_userprofile_detected_insecure_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEquipmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_item_object_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(choices=[('ADDED', 'Added'), ('REMOVED', 'Removed')], max_length=32)),
                ('equipment_item_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrobin.Image')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddIndex(
            model_name='imageequipmentlog',
            index=models.Index(fields=['equipment_item_content_type', 'equipment_item_object_id', 'image', 'date'], name='astrobin_im_equipme_b0d8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='imageequipmentlog',
            index=models.Index(fields=['image'], name='astrobin_im_image_i_a3d1e2_idx'),
        ),
    ]
