# Generated by Django 2.2.24 on 2023-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0184_add_image_equipment_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepsky_acquisition',
            name='bortle',
            field=models.DecimalField(blank=True,
                choices=[(1, '1 - Excellent dark-site sky (BLACK)'), (2, '2 - Typical truly dark site (GRAY)'),
                         (3, '3 - Rural sky (BLUE)'), (4, '4 - Rural/suburban transition (GREEN/YELLOW)'),
                         (4.5, '4.5 - Semi-Suburban/Transition sky (YELLOW)'), (5, '5 - Suburban sky (ORANGE)'),
                         (6, '6 - Bright suburban sky (RED)'), (7, '7 - Suburban/urban transition or Full Moon (RED)'),
                         (8, '8 - City sky (WHITE)'), (9, '9 - Inner city sky (WHITE)')], decimal_places=1,
                help_text='Quality of the sky according to <a href="http://en.wikipedia.org/wiki/Bortle_Dark-Sky_Scale" target="_blank">the Bortle Scale</a>.',
                max_digits=2, null=True, verbose_name='Bortle Dark-Sky Scale'
            ),
        ),
    ]
