# Generated by Django 2.2.24 on 2024-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0187_add_trevinca_skies_to_remote_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='disqualified_from_iotd_tp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
