# Generated by Django 2.2.24 on 2024-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0190_add_landscape_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='skip_activity_stream',
            field=models.NullBooleanField(
                default=None, help_text="Do not create an entry on the front page's activity stream for this event.",
                verbose_name='Skip activity stream'
            ),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='skip_activity_stream',
            field=models.NullBooleanField(
                default=None, help_text="Do not create an entry on the front page's activity stream for this event.",
                verbose_name='Skip activity stream'
            ),
        ),
    ]
