# Generated by Django 2.2.24 on 2024-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0194_userprofile_contribution_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='constellation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
