# Generated by Django 2.2.24 on 2024-02-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0195_image_constellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='final_gallery_thumbnail',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
