# Generated by Django 2.2.24 on 2024-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0197_add_followers_counts_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
