# Generated by Django 2.2.24 on 2024-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0201_add_howling_coyote_remote_observatories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='insufficiently_active_iotd_staff_member_reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
