# Generated by Django 2.2.24 on 2024-03-16 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin', '0202_userprofile_insufficiently_active_iotd_staff_member_reminders_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pending_collaborators',
            field=models.ManyToManyField(
                blank=True, related_name='images_as_pending_collaborator', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
