# Generated by Django 2.2.24 on 2024-07-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0205_userprofile_agreed_to_marketplace_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_notification_update',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
