# Generated by Django 2.2.24 on 2024-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0207_add_artificial_satellite_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
