# Generated by Django 2.2.24 on 2024-08-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0213_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerevision',
            name='constellation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
