# Generated by Django 2.2.24 on 2024-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0216_make_new_search_experience_default_for_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gallery_header_image',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True),
        ),
    ]
