# Generated by Django 2.2.24 on 2024-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0217_userprofile_gallery_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
