# Generated by Django 2.2.24 on 2024-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0218_collection_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_count_including_wip',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
