# Generated by Django 2.2.24 on 2024-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0219_collection_image_count_including_wip'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='nested_collection_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
