# Generated by Django 2.2.24 on 2024-10-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0222_userprofile_enable_new_gallery_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='may_enable_new_gallery_experience',
            field=models.NullBooleanField(default=None, editable=False),
        ),
    ]
