# Generated by Django 2.2.24 on 2024-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0225_add_action_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_allow_image_adjustments_widget',
            field=models.BooleanField(default=True, help_text='If you disable this option, the image adjustments widget will not be shown on your images. This setting only affects the new gallery and search experiences.', verbose_name='Allow image adjustments widget on your images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_max_zoom',
            field=models.SmallIntegerField(choices=[(8, '8x'), (4, '4x'), (2, '2x'), (1, '1x')], default=8, help_text='Select the maximum zoom allowed on your images. 1x refers to the native resolution of an image. This setting only affects the new gallery and search experiences.', verbose_name='Maximum zoom allowed on your images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_collections_on_public_gallery',
            field=models.BooleanField(default=True, help_text='Select if you want your collections to be displayed on your public gallery. If you disable this, your collections will be displayed separately. This setting only affects the new gallery experience.', verbose_name='Display collections on your public gallery'),
        ),
    ]
