# Generated by Django 2.2.24 on 2024-12-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0226_add_default_settings_for_image_adjustments_zoom_and_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='allow_image_adjustments_widget',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='max_zoom',
            field=models.SmallIntegerField(choices=[(8, '8x'), (4, '4x'), (2, '2x'), (1, '1x')], null=True, blank=True),
        ),
    ]
