# Generated by Django 2.2.24 on 2025-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0228_add_AAA_remote_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_collections_on_public_gallery',
            field=models.BooleanField(
                default=False,
                help_text='Select if you want your collections to be displayed on your public gallery. If you disable this, your collections will be displayed separately. This setting only affects the new gallery experience.',
                verbose_name='Display collections on your public gallery'
            ),
        ),
    ]
