# Generated by Django 2.2.24 on 2025-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0229_make_display_collections_on_public_gallery_default_to_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
