# Generated by Django 2.2.24 on 2025-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0232_update_countries_and_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True,
                choices=[('en', 'English (US)'), ('en-GB', 'English (GB)'), ('it', 'Italian'), ('es', 'Spanish'),
                         ('fr', 'French'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('de', 'German'), ('nl', 'Dutch'),
                         ('tr', 'Turkish'), ('sq', 'Albanian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('el', 'Greek'),
                         ('uk', 'Ukrainian'), ('ru', 'Russian'), ('be', 'Belarusian'), ('ja', 'Japanese'),
                         ('zh-hans', 'Chinese (Simplified)'), ('hu', 'Hungarian')], max_length=8, null=True,
                verbose_name='Language'
            ),
        ),
    ]
