# Generated by Django 2.2.24 on 2025-03-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin', '0233_remove_arabic_from_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enable_new_gallery_experience',
            field=models.NullBooleanField(
                default=True,
                help_text='Enable the new gallery experience, with improved navigation and a new image viewer. <a href="https://welcome.astrobin.com/blog/introducing-the-new-astrobin-gallery-experience" target="_blank">Learn more</a>',
                verbose_name='Enable new gallery experience'
            ),
        ),
    ]
