sudo: required
dist: trusty

services:
  - docker

env:
  - NGINX_MODE=dev


before_install:
  - ulimit -s 1082768
  - sudo /etc/init.d/postgresql stop

install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - docker build --no-cache -t astrobin/nginx-${NGINX_MODE}:latest -f docker/nginx.${NGINX_MODE}.dockerfile .
  - docker build --no-cache -t astrobin/astrobin:latest -f docker/astrobin.dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml up -d

before_script:
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml run --no-deps --rm astrobin ./scripts/init.sh

script:
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml run --no-deps --rm astrobin bash -c "./manage.py collectstatic --noinput && ./scripts/test.sh"

after_success:
  - docker cp -a .git $(docker ps -q -f name=astrobin_astrobin --last 1):/code # Needed by codecov.
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml exec astrobin ./scripts/codecov.sh
  - docker push astrobin/nginx-${NGINX_MODE}:latest
  - docker push astrobin/astrobin:latest

after_script:
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml down
  - docker logout

