sudo: required
dist: trusty

services:
  - docker

env:
  - NGINX_MODE=dev

before_install:
  - ulimit -s 1082768

install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - docker build --no-cache -t astrobin/nginx-${NGINX_MODE}:latest -f docker/nginx.${NGINX_MODE}.dockerfile .
  - docker build --no-cache -t astrobin/astrobin:latest -f docker/astrobin.dockerfile .

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml up -d
  - docker exec -it docker_astrobin_1 ./manage.py collectstatic --noinput --verbosity 0

script:
  - docker exec -it docker_astrobin_1 ./scripts/test.sh

after_success:
  - docker cp -a .git docker_astrobin_1:/code # Needed by codecov.
  - docker exec -it docker_astrobin_1 ./scripts/codecov.sh
  - docker push astrobin/nginx-${NGINX_MODE}:latest
  - docker push astrobin/astrobin:latest

after_script:
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml -f docker/docker-compose.travis.yml down
  - docker logout

