sudo: required
dist: xenial

services:
  - docker

install:
  # Make sure docker packages build even tho we don't use them on Travis because of memory issues.
  # - docker build --no-cache -t astrobin/nginx-dev:latest -f docker/nginx.dev.dockerfile .
  # - docker build --no-cache -t astrobin/astrobin:latest -f docker/astrobin.dockerfile .
  - ./ci/install.sh

before_script:
  - ./ci/prepare.sh

script:
  - ./ci/test.sh

after_success:
  - ./scripts/codecov.sh
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push astrobin/nginx-dev:latest
  # - docker push astrobin/astrobin:latest

# after_script:
  # - docker logout
