version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - buildspecs/install-docker.sh
      - npm ci
      - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}


  build:
    commands:
      - buildspecs/build.sh
      - buildspecs/test.sh

  post_build:
    commands:
      - buildspecs/push-image.sh
