version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - |
        docker build --no-cache \
            -t astrobin/astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION \
            -f docker/astrobin.dockerfile .
      - |
        docker run astrobin/astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION bash -c "\
            USE_SQLITE=true TESTING=true ./scripts/test.sh && \
            coverage xml && \
            codecov --commit=$CODEBUILD_RESOLVED_SOURCE_VERSION -t $CODECOV_TOKEN"

  post_build:
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push astrobin/astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker logout
