version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - buildspecs/install-docker.sh
      - buildspecs/build.sh

  post_build:
    commands:
      - buildspecs/push-image.sh
