version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - docker build -t astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION -f docker/astrobin.dockerfile .
      - docker run astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION bash -c "\
           ./scripts/test.sh && \
           coverage xml && \
           codecov --commit=$CODEBUILD_RESOLVED_SOURCE_VERSION -t $CODECOV_TOKEN"
      - exec 3< <(sudo docker compose -f docker/docker-compose.yml -f docker/docker-compose.build.yml up)
      - sed '/[INFO] Listening at/q' <&3 ; cat <&3 &
      - docker exec -it docker_astrobin_1 bash -c "npm ci && CYPRESS_baseUrl=http://localhost:8083 $(npm bin)/cypress run"
      - docker tag astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URL/astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - |
        aws ecr get-login-password --region us-east-1 | docker login \
           --username AWS \
           --password-stdin \
            $ECR_URL
      - docker push $ECR_URL/astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION
