version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - docker build -t astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION -f docker/astrobin.dockerfile .
      - |
        aws ecr get-login-password --region us-east-1 | docker login \
            --username AWS \
            --password-stdin \
            $ECR_URL
      - docker push $ECR_URL/astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION
