version: 0.2

phases:
  install:
    commands:
      - # https://github.com/yarnpkg/yarn/issues/7866
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get -y update
      - apt-get -y install jq

  build:
    commands:
      - buildspecs/deploy.sh astrobin-app-launch-template astrobin-app-autoscaling-group 540
      - buildspecs/deploy.sh astrobin-worker-launch-template astrobin-worker-autoscaling-group 60
      - buildspecs/deploy.sh astrobin-scheduler-launch-template astrobin-scheduler-autoscaling-group 60
