version: 0.2

phases:
  install:
    commands:
      - # https://github.com/yarnpkg/yarn/issues/7866
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get -y update
      - apt-get -y install jq

  build:
    commands:
      - buildspecs/install-docker.sh
      - buildspecs/deploy-update-version.sh astrobin-app-launch-template
      - buildspecs/deploy-app.sh astrobin-app-launch-template astrobin-app-autoscaling-group 420
      - buildspecs/deploy-update-version.sh astrobin-worker-launch-template
      - buildspecs/deploy-other.sh astrobin-worker-launch-template astrobin-worker-autoscaling-group 300
      - buildspecs/deploy-update-version.sh astrobin-scheduler-launch-template
      - buildspecs/deploy-other.sh astrobin-scheduler-launch-template astrobin-scheduler-autoscaling-group 60
      - buildspecs/deploy-update-version.sh astrobin-flower-launch-template
      - buildspecs/deploy-other.sh astrobin-flower-launch-template astrobin-flower-autoscaling-group 60
      - buildspecs/deploy-update-version.sh astrobin-equipment-indexer-launch-template
