version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - docker pull $ECR_URL/astrobin:latest
      - |
        docker run astrobin:$CODEBUILD_RESOLVED_SOURCE_VERSION bash -c "\
            ./scripts/test.sh && \
            coverage xml && \
            codecov --commit=$CODEBUILD_RESOLVED_SOURCE_VERSION -t $CODECOV_TOKEN"
