# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-08 20:48
from __future__ import unicode_literals

import common.upload_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CkEditorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(max_length=1024, upload_to=common.upload_paths.upload_path)),
                ('filename', models.CharField(max_length=256)),
                ('filesize', models.PositiveIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
