# Generated by Django 2.2.24 on 2023-01-29 16:36

import astrobin_apps_json_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_json_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckeditorfile',
            name='upload',
            field=models.FileField(max_length=1024, upload_to=astrobin_apps_json_api.models.ckeditor_upload_path),
        ),
    ]
