# Generated by Django 2.2.24 on 2023-11-17 19:17

import astrobin_apps_json_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_json_api', '0002_alter_field_ckeditorfile_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckeditorfile',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=astrobin_apps_json_api.models.ckeditor_thumbnail_upload_path),
        ),
    ]
