# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-09 23:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='skyplot_zoom1',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/skyplots'),
        ),
    ]
