# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0002_auto_20171109_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='pixinsight_serial_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='pixinsight_svg_annotation',
            field=models.ImageField(blank=True, null=True, upload_to=b'pixinsight-solutions'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, b'Missing'), (1, b'Pending'), (2, b'Failed'), (3, b'Success'), (4, b'Advanced pending'), (5, b'Advanced failed'), (6, b'Advanced success')], default=0),
        ),
    ]
