# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0003_pixinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='advanced_dec_matrix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_matrix_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_matrix_rect',
            field=models.CharField(blank=True, max_length=131, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_ra_matrix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
