# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0003_pixinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='advanced_dec',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_orientation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_pixscale',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_ra',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
