# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0004_pixinsight_astrometry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='advanced_dec_bottom_left',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_dec_bottom_right',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_dec_top_left',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_dec_top_right',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_flipped',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_ra_bottom_left',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_ra_bottom_right',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_ra_top_left',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_ra_top_right',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_wcs_transformation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
