# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0005_solution_pixinsight_svg_annotation_620'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateSolvingAdvancedSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_grid', models.BooleanField(default=True, verbose_name='Show equatorial grid')),
                ('show_constellation_borders', models.BooleanField(default=True, verbose_name='Show constellation borders')),
                ('show_constellation_lines', models.BooleanField(default=True, verbose_name='Show constellation lines')),
                ('show_named_stars', models.BooleanField(default=True, verbose_name='Show named stars')),
                ('show_messier', models.BooleanField(default=True, verbose_name='Show Messier objects')),
                ('show_ngc_ic', models.BooleanField(default=True, verbose_name='Show NGC and IC objects')),
                ('show_vdb', models.BooleanField(default=True, verbose_name='Show VdB objects')),
                ('show_sharpless', models.BooleanField(default=True, verbose_name='Show Sharpless objects')),
                ('show_barnard', models.BooleanField(default=True, verbose_name='Show Barnard objects')),
                ('show_pgc', models.BooleanField(default=False, verbose_name='Show PGC objects')),
                ('show_planets', models.BooleanField(default=True, help_text='Only available if your image at least an acquisition time and an accurate location', verbose_name='Show planets')),
                ('show_asteroids', models.BooleanField(default=True, help_text='Only available if your image at least an acquisition time and an accurate location', verbose_name='Show asteroids')),
                ('show_gcvs', models.BooleanField(default=False, help_text='General Catalog of Variable Stars', verbose_name='Show GCVS stars')),
                ('show_gaia_dr2', models.BooleanField(default=False, help_text=b'<a href="https://wikipedia.org/wiki/Gaia_(spacecraft)" target="_blank">https://wikipedia.org/wiki/Gaia_(spacecraft)</a>', verbose_name='Show Gaia DR2 objects')),
                ('show_ppmxl', models.BooleanField(default=False, help_text=b'<a href="https://arxiv.org/abs/1003.5852" target="_blank">https://arxiv.org/abs/1003.5852</a>', verbose_name='Show PPMXL catalog')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='astrobin_apps_platesolving.PlateSolvingAdvancedSettings'),
        ),
    ]
