# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0007_platesolvingadvancedsettings_sample_raw_frame_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='pixinsight_svg_annotation',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='pixinsight_svg_annotation_620',
        ),
        migrations.AddField(
            model_name='solution',
            name='pixinsight_svg_annotation_hd',
            field=models.ImageField(blank=True, null=True, upload_to=b'pixinsight-solutions-hd'),
        ),
        migrations.AddField(
            model_name='solution',
            name='pixinsight_svg_annotation_regular',
            field=models.ImageField(blank=True, null=True, upload_to=b'pixinsight-solutions-regular'),
        ),
    ]
