# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0011_update_platesolvingadvanced_settings_sample_raw_frame_file_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateSolvingAdvancedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('task_params', models.TextField()),
            ],
        ),
    ]
