# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0013_remove_gaia_ppmxl_add_tycho_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesolvingadvancedsettings',
            name='show_cgpn',
            field=models.BooleanField(default=True,
                                      help_text=b'<a href="https://ui.adsabs.harvard.edu/abs/2001A%26A...378..843K/abstract">Catalogue of Galactic Planetary Nebulae</a>',
                                      verbose_name='Show CGPN objects'),
        ),
    ]
