# Generated by Django 2.2.24 on 2021-07-06 09:53

import astrobin_apps_platesolving.models
import common.validators.file_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0015_update_sample_raw_frame_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='sample_raw_frame_file',
            field=models.FileField(blank=True, help_text='To improve the accuracy of your plate-solution even further, please upload one of the XISF or FITS files from your data set. Such files normally have date and time headers that will allow AstroBin to calculate solar system body ephemerides and find planets and asteroids in your image (provided you also add location information to it).<br/><br/>For maximum accuracy, it\'s recommended that you use PixInsight\'s native and open format XISF. Learn more about XISF here:<br/><br/><a href="https://pixinsight.com/xisf/" target="_blank">https://pixinsight.com/xisf/</a><br/><br/> <strong>Please note:</strong> it\'s very important that the XISF or FITS file you upload is aligned to your processed image, otherwise the object annotations will not match. To improve your chances at a successful accurate plate-solution, calibrate your file the usual way (dark/bias/flats) but do not stretch it.', max_length=256, null=True, upload_to=astrobin_apps_platesolving.models.sample_frame_upload_path, validators=[common.validators.file_validator.FileValidator(allowed_extensions=('xisf', 'fits', 'fit', 'fts'))], verbose_name='Sample raw frame (max 100 MB)'),
        ),
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='scaled_font_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', help_text='Font size of the annotations on your main image page', max_length=1, verbose_name='Scaled font size'),
        ),
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='show_cgpn',
            field=models.BooleanField(default=True, help_text='<a href="https://ui.adsabs.harvard.edu/abs/2001A%26A...378..843K/abstract">Catalogue of Galactic Planetary Nebulae</a>', verbose_name='Show CGPN objects'),
        ),
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='show_tycho_2',
            field=models.BooleanField(default=False, help_text='<a href="https://wikipedia.org/wiki/Tycho-2_Catalogue" target="_blank">https://wikipedia.org/wiki/Tycho-2_Catalogue</a>', verbose_name='Show Tycho-2 catalog'),
        ),
        migrations.AlterField(
            model_name='platesolvingsettings',
            name='scale_units',
            field=models.CharField(blank=True, choices=[('degwidth', 'Width of the field in degrees'), ('arcminwidth', 'Width of the field in arcminutes'), ('arcsecperpix', 'Resolution of the field in arcseconds/pixel')], help_text='The units for the min/max field size settings below.', max_length=16, null=True, verbose_name='Field size units'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='solutions'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='pixinsight_svg_annotation_hd',
            field=models.ImageField(blank=True, null=True, upload_to='pixinsight-solutions-hd'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='pixinsight_svg_annotation_regular',
            field=models.ImageField(blank=True, null=True, upload_to='pixinsight-solutions-regular'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='skyplot_zoom1',
            field=models.ImageField(blank=True, null=True, upload_to='images/skyplots'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Missing'), (1, 'Pending'), (2, 'Failed'), (3, 'Success'), (4, 'Advanced pending'), (5, 'Advanced failed'), (6, 'Advanced success')], default=0),
        ),
    ]
