# Generated by Django 2.2.24 on 2021-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0016_add_solution_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesolvingadvancedtask',
            name='error_message',
            field=models.CharField(editable=False, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='platesolvingadvancedtask',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('ERROR', 'ERROR')], editable=False, max_length=8, null=True),
        ),
    ]
