# Generated by Django 2.2.24 on 2021-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0017_platesolvingadvancedtask_add_status_and_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesolvingadvancedsettings',
            name='show_lbn',
            field=models.BooleanField(default=True,
                                      verbose_name="Show objects from the Lynds' Catalogue of Bright Nebulae (LBN) (Lynds 1965)"),
        ),
        migrations.AddField(
            model_name='platesolvingadvancedsettings',
            name='show_ldn',
            field=models.BooleanField(default=True,
                                      verbose_name="Show objects from the Lynds' Catalogue of Dark Nebulae (LDN) (Lynds 1962)"),
        ),
        migrations.AddField(
            model_name='platesolvingadvancedsettings',
            name='show_quasars',
            field=models.BooleanField(default=False,
                                      help_text='<a href="https://heasarc.gsfc.nasa.gov/W3Browse/all/milliquas.html">MILLIQUAS - Million Quasars Catalog</a>',
                                      verbose_name='Show quasars'),
        ),
    ]
