# Generated by Django 2.2.24 on 2021-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0018_add_lbn_ldn_quasars_catalogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='show_cgpn',
            field=models.BooleanField(default=True,
                                      help_text='<a href="https://ui.adsabs.harvard.edu/abs/2001A%26A...378..843K/abstract">Catalogue of Galactic Planetary Nebulae</a>',
                                      verbose_name='Show CGPN objects'),
        ),
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='show_tycho_2',
            field=models.BooleanField(default=False,
                                      help_text='<a href="https://wikipedia.org/wiki/Tycho-2_Catalogue" target="_blank">https://wikipedia.org/wiki/Tycho-2_Catalogue</a>',
                                      verbose_name='Show Tycho-2 catalog'),
        ),
        migrations.AlterField(
            model_name='platesolvingsettings',
            name='scale_units',
            field=models.CharField(blank=True, choices=[('degwidth', 'Width of the field in degrees'),
                                                        ('arcminwidth', 'Width of the field in arcminutes'), (
                                                        'arcsecperpix', 'Resolution of the field in arcseconds/pixel')],
                                   help_text='The units for the min/max field size settings below.', max_length=16,
                                   null=True, verbose_name='Field size units'),
        ),
    ]
