# Generated by Django 2.2.24 on 2021-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0021_add_plate_solving_advanced_live_log_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='pixinsight_finding_chart',
            field=models.ImageField(blank=True, null=True, upload_to='pixinsight-finding-charts'),
        ),
        migrations.AddField(
            model_name='solution',
            name='pixinsight_finding_chart_small',
            field=models.ImageField(blank=True, null=True, upload_to='pixinsight-finding-charts'),
        ),
    ]
