# Generated by Django 2.2.24 on 2022-10-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0023_add_show_hd_and_max_magnitude_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
