# Generated by Django 2.2.24 on 2022-10-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0024_make_solution_object_id_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='object_id',
            field=models.TextField(),
        ),
    ]
