# Generated by Django 2.2.24 on 2023-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_platesolving', '0024_add_downsample_factor_and_use_sextractor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesolvingadvancedsettings',
            name='hd_max_magnitude',
            field=models.DecimalField(
                blank=True, decimal_places=2, default=9,
                help_text="Only HD stars up to this magnitude will be rendered. If left empty, the catalog's default value will be used.",
                max_digits=4, null=True, verbose_name='Max. magnitude'
            ),
        ),
    ]
