# Generated by Django 2.2.24 on 2024-07-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0025_add_default_to_hd_magnitude_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesolvingadvancedsettings',
            name='show_ecliptic',
            field=models.BooleanField(default=True, verbose_name='Show ecliptic'),
        ),
        migrations.AddField(
            model_name='platesolvingadvancedsettings',
            name='show_galactic_equator',
            field=models.BooleanField(default=True, verbose_name='Show galactic equator'),
        ),
    ]
