# Generated by Django 2.2.24 on 2024-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0026_add_ecliptic_and_galactic_equator_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
