# Generated by Django 2.2.24 on 2024-10-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0027_add_solution_attempts_and_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesolvingsettings',
            name='astrometry_net_publicly_visible',
            field=models.BooleanField(default=False, help_text="If checked, the astrometry.net submission will be publicly visible. If you leave this unchecked,you won't be able to see the full log of the astrometry.net submission, but the image will stillbe plate-solved and annotated.", verbose_name='Publicly visible astrometry.net submission'),
        ),
    ]
