# Generated by Django 2.2.24 on 2025-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_platesolving', '0029_make_default_hd_max_magnitude_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='platesolvingadvancedtask',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10),
        ),
    ]
