# Generated by Django 2.2.24 on 2021-08-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('SPAM', 'This content is spam and/or fraudulent'), ('OFFENSIVE', 'This content is offensive (e.g. hate speech, harassment, violence, bullying, mocking, etc...'), ('IP', "This content infringes on someone's intellectual property"), ('OTHER', 'Other')], max_length=16, null=True, verbose_name='Reason')),
                ('moderation_datetime', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed'), ('OVERRULED', 'Overruled')], max_length=16, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports_moderated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to=settings.AUTH_USER_MODEL)),
                ('additional_information', models.CharField(blank=True, max_length=500, null=True, verbose_name='Additional information (optional)')),
            ],
        ),
    ]
