# Generated by Django 2.2.24 on 2021-08-17 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nested_comments', '0003_add_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_abuse_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_abuse_objects_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_moderated_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_moderator_decision',
            field=models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed'), ('OVERRULED', 'Overruled')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_reason',
            field=models.CharField(blank=True, choices=[('SPAM', 'This content is spam and/or fraudulent'), ('OFFENSIVE', 'This content is offensive (e.g. hate speech, harassment, violence, bullying, mocking, etc...'), ('IP', "This content infringes on someone's intellectual property"), ('OTHER', 'Other')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='report_abuse_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
