class SubjectType:
    DEEP_SKY = "DEEP_SKY"
    SOLAR_SYSTEM = "SOLAR_SYSTEM"
    WIDE_FIELD = "WIDE_FIELD"
    STAR_TRAILS = "STAR_TRAILS"
    NORTHERN_LIGHTS = "NORTHERN_LIGHTS"
    GEAR = "GEAR"
    OTHER = "OTHER"
