/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Xapian {

using System;
using System.Runtime.InteropServices;

public class PostingSource : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PostingSource(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PostingSource obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PostingSource() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XapianPINVOKE.delete_PostingSource(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  protected PostingSource() : this(XapianPINVOKE.new_PostingSource(), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  public virtual uint GetTermfreqMin() {
    uint ret = XapianPINVOKE.PostingSource_GetTermfreqMin(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint GetTermfreqEst() {
    uint ret = XapianPINVOKE.PostingSource_GetTermfreqEst(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint GetTermfreqMax() {
    uint ret = XapianPINVOKE.PostingSource_GetTermfreqMax(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetMaxweight() {
    double ret = XapianPINVOKE.PostingSource_GetMaxweight(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetWeight() {
    double ret = (SwigDerivedClassHasMethod("GetWeight", swigMethodTypes3) ? XapianPINVOKE.PostingSource_GetWeightSwigExplicitPostingSource(swigCPtr) : XapianPINVOKE.PostingSource_GetWeight(swigCPtr));
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint GetDocId() {
    uint ret = XapianPINVOKE.PostingSource_GetDocId(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Next(double min_wt) {
    XapianPINVOKE.PostingSource_Next(swigCPtr, min_wt);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SkipTo(uint did, double min_wt) {
    if (SwigDerivedClassHasMethod("SkipTo", swigMethodTypes6)) XapianPINVOKE.PostingSource_SkipToSwigExplicitPostingSource(swigCPtr, did, min_wt); else XapianPINVOKE.PostingSource_SkipTo(swigCPtr, did, min_wt);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool Check(uint did, double min_wt) {
    bool ret = (SwigDerivedClassHasMethod("Check", swigMethodTypes7) ? XapianPINVOKE.PostingSource_CheckSwigExplicitPostingSource(swigCPtr, did, min_wt) : XapianPINVOKE.PostingSource_Check(swigCPtr, did, min_wt));
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool AtEnd() {
    bool ret = XapianPINVOKE.PostingSource_AtEnd(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string Name() {
    string ret = (SwigDerivedClassHasMethod("Name", swigMethodTypes9) ? XapianPINVOKE.PostingSource_NameSwigExplicitPostingSource(swigCPtr) : XapianPINVOKE.PostingSource_Name(swigCPtr));
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Init(Database db) {
    XapianPINVOKE.PostingSource_Init(swigCPtr, Database.getCPtr(db));
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string GetDescription() {
    string ret = (SwigDerivedClassHasMethod("GetDescription", swigMethodTypes11) ? XapianPINVOKE.PostingSource_GetDescriptionSwigExplicitPostingSource(swigCPtr) : XapianPINVOKE.PostingSource_GetDescription(swigCPtr));
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("GetTermfreqMin", swigMethodTypes0))
      swigDelegate0 = new SwigDelegatePostingSource_0(SwigDirectorGetTermfreqMin);
    if (SwigDerivedClassHasMethod("GetTermfreqEst", swigMethodTypes1))
      swigDelegate1 = new SwigDelegatePostingSource_1(SwigDirectorGetTermfreqEst);
    if (SwigDerivedClassHasMethod("GetTermfreqMax", swigMethodTypes2))
      swigDelegate2 = new SwigDelegatePostingSource_2(SwigDirectorGetTermfreqMax);
    if (SwigDerivedClassHasMethod("GetWeight", swigMethodTypes3))
      swigDelegate3 = new SwigDelegatePostingSource_3(SwigDirectorGetWeight);
    if (SwigDerivedClassHasMethod("GetDocId", swigMethodTypes4))
      swigDelegate4 = new SwigDelegatePostingSource_4(SwigDirectorGetDocId);
    if (SwigDerivedClassHasMethod("Next", swigMethodTypes5))
      swigDelegate5 = new SwigDelegatePostingSource_5(SwigDirectorNext);
    if (SwigDerivedClassHasMethod("SkipTo", swigMethodTypes6))
      swigDelegate6 = new SwigDelegatePostingSource_6(SwigDirectorSkipTo);
    if (SwigDerivedClassHasMethod("Check", swigMethodTypes7))
      swigDelegate7 = new SwigDelegatePostingSource_7(SwigDirectorCheck);
    if (SwigDerivedClassHasMethod("AtEnd", swigMethodTypes8))
      swigDelegate8 = new SwigDelegatePostingSource_8(SwigDirectorAtEnd);
    if (SwigDerivedClassHasMethod("Name", swigMethodTypes9))
      swigDelegate9 = new SwigDelegatePostingSource_9(SwigDirectorName);
    if (SwigDerivedClassHasMethod("Init", swigMethodTypes10))
      swigDelegate10 = new SwigDelegatePostingSource_10(SwigDirectorInit);
    if (SwigDerivedClassHasMethod("GetDescription", swigMethodTypes11))
      swigDelegate11 = new SwigDelegatePostingSource_11(SwigDirectorGetDescription);
    XapianPINVOKE.PostingSource_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(PostingSource));
    return hasDerivedMethod;
  }

  private uint SwigDirectorGetTermfreqMin() {
    return GetTermfreqMin();
  }

  private uint SwigDirectorGetTermfreqEst() {
    return GetTermfreqEst();
  }

  private uint SwigDirectorGetTermfreqMax() {
    return GetTermfreqMax();
  }

  private double SwigDirectorGetWeight() {
    return GetWeight();
  }

  private uint SwigDirectorGetDocId() {
    return GetDocId();
  }

  private void SwigDirectorNext(double min_wt) {
    Next(min_wt);
  }

  private void SwigDirectorSkipTo(uint did, double min_wt) {
    SkipTo(did, min_wt);
  }

  private bool SwigDirectorCheck(uint did, double min_wt) {
    return Check(did, min_wt);
  }

  private bool SwigDirectorAtEnd() {
    return AtEnd();
  }

  private string SwigDirectorName() {
    return Name();
  }

  private void SwigDirectorInit(IntPtr db) {
    Init(new Database(db, false));
  }

  private string SwigDirectorGetDescription() {
    return GetDescription();
  }

  public delegate uint SwigDelegatePostingSource_0();
  public delegate uint SwigDelegatePostingSource_1();
  public delegate uint SwigDelegatePostingSource_2();
  public delegate double SwigDelegatePostingSource_3();
  public delegate uint SwigDelegatePostingSource_4();
  public delegate void SwigDelegatePostingSource_5(double min_wt);
  public delegate void SwigDelegatePostingSource_6(uint did, double min_wt);
  public delegate bool SwigDelegatePostingSource_7(uint did, double min_wt);
  public delegate bool SwigDelegatePostingSource_8();
  public delegate string SwigDelegatePostingSource_9();
  public delegate void SwigDelegatePostingSource_10(IntPtr db);
  public delegate string SwigDelegatePostingSource_11();

  private SwigDelegatePostingSource_0 swigDelegate0;
  private SwigDelegatePostingSource_1 swigDelegate1;
  private SwigDelegatePostingSource_2 swigDelegate2;
  private SwigDelegatePostingSource_3 swigDelegate3;
  private SwigDelegatePostingSource_4 swigDelegate4;
  private SwigDelegatePostingSource_5 swigDelegate5;
  private SwigDelegatePostingSource_6 swigDelegate6;
  private SwigDelegatePostingSource_7 swigDelegate7;
  private SwigDelegatePostingSource_8 swigDelegate8;
  private SwigDelegatePostingSource_9 swigDelegate9;
  private SwigDelegatePostingSource_10 swigDelegate10;
  private SwigDelegatePostingSource_11 swigDelegate11;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] {  };
  private static Type[] swigMethodTypes2 = new Type[] {  };
  private static Type[] swigMethodTypes3 = new Type[] {  };
  private static Type[] swigMethodTypes4 = new Type[] {  };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(double) };
  private static Type[] swigMethodTypes6 = new Type[] { typeof(uint), typeof(double) };
  private static Type[] swigMethodTypes7 = new Type[] { typeof(uint), typeof(double) };
  private static Type[] swigMethodTypes8 = new Type[] {  };
  private static Type[] swigMethodTypes9 = new Type[] {  };
  private static Type[] swigMethodTypes10 = new Type[] { typeof(Database) };
  private static Type[] swigMethodTypes11 = new Type[] {  };
}

}
