# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-17 12:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrobin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real', models.CharField(blank=True, max_length=512, null=True)),
                ('real_inverted', models.CharField(blank=True, max_length=512, null=True)),
                ('hd', models.CharField(blank=True, max_length=512, null=True)),
                ('hd_inverted', models.CharField(blank=True, max_length=512, null=True)),
                ('regular', models.CharField(blank=True, max_length=512, null=True)),
                ('regular_inverted', models.CharField(blank=True, max_length=512, null=True)),
                ('gallery', models.CharField(blank=True, max_length=512, null=True)),
                ('gallery_inverted', models.CharField(blank=True, max_length=512, null=True)),
                ('collection', models.CharField(blank=True, max_length=512, null=True)),
                ('thumb', models.CharField(blank=True, max_length=512, null=True)),
                ('revision', models.CharField(blank=True, max_length=512, null=True)),
                ('histogram', models.CharField(blank=True, max_length=512, null=True)),
                ('iotd', models.CharField(blank=True, max_length=512, null=True)),
                ('iotd_candidate', models.CharField(blank=True, max_length=512, null=True)),
                ('story', models.CharField(blank=True, max_length=512, null=True)),
                ('duckduckgo', models.CharField(blank=True, max_length=512, null=True)),
                ('duckduckgo_small', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='astrobin.Image')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='thumbnailgroup',
            unique_together=set([('image', 'revision')]),
        ),
    ]
