# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-26 20:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailgroup',
            name='hd_anonymized',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
