# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0002_thumbnailgroup_hd_anonymized'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyvaluetags', to='astrobin.Image')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='keyvaluetag',
            unique_together=set([('image', 'key')]),
        ),
    ]
