# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0003_add_key_value_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailgroup',
            name='hd_sharpened',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='regular_sharpened',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnailgroup',
            name='revision',
            field=models.CharField(default=b'0', max_length=3),
        ),
    ]
