# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0007_thumbnailgroup_iotd_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailgroup',
            name='instagram_story',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
