# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-29 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0011_thumbnailgroup_real_anonymized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnailgroup',
            old_name='regular_crop_anonymized',
            new_name='story_crop',
        ),
    ]
