# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0012_rename_regular_crop_anonymized_to_story_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailgroup',
            name='regular_large',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='regular_large_anonymized',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='regular_large_inverted',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='regular_large_sharpened',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='regular_large_sharpened_inverted',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
