# Generated by Django 2.2.24 on 2022-02-10 08:19

from django.db import migrations, models

import common.upload_paths
import common.validators.file_validator


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_images', '0013_add_regular_large_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncompressedsourceupload',
            name='uncompressed_source_file',
            field=models.FileField(
                help_text='You can store the final processed image that came out of your favorite image editor (e.g. '
                          'PixInsight, Adobe Photoshop, etc) here on AstroBin, for archival purposes. This file is '
                          'stored privately and only you will have access to it.',
                max_length=256,
                null=True,
                upload_to=common.upload_paths.uncompressed_source_upload_path,
                validators=[
                    common.validators.file_validator.FileValidator(
                        allowed_extensions=('xisf', 'fits', 'fit', 'fts', 'psd', 'tif', 'tiff')
                    )
                ],
                verbose_name='Uncompressed source (max 100 MB)'
            ),
        ),
    ]
