# Generated by Django 2.2.24 on 2022-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0014_alter_uncompressed_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailgroup',
            name='qhd',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='qhd_anonymized',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='qhd_inverted',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='qhd_sharpened',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='thumbnailgroup',
            name='qhd_sharpened_inverted',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
