# Generated by Django 2.2.24 on 2023-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_images', '0015_add_qhd_thumbnail_group_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailgroup',
            name='hd_anonymized_crop',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
