/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class KeyMaker {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public KeyMaker(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(KeyMaker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_KeyMaker(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XapianJNI.KeyMaker_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XapianJNI.KeyMaker_change_ownership(this, swigCPtr, true);
  }

  public String apply(Document doc) {
    return XapianJNI.KeyMaker_apply(swigCPtr, this, Document.getCPtr(doc), doc);
  }

  public KeyMaker() {
    this(XapianJNI.new_KeyMaker(), true);
    XapianJNI.KeyMaker_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
