version: '3'

# This file is meant to be used by docker-compose to build images locally. It's useful for development.

services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx.${NGINX_MODE}.dockerfile


  astrobin:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    command: bash -c "./manage.py migrate --noinput && ./manage.py collectstatic --noinput && gunicorn wsgi:application -w 4 -b :8083 --max-requests 1000 --max-requests-jitter 50 --timeout 300 --graceful-timeout 300 -k gevent"
    ports:
      - "8083:8083"
      - "8084:8084"
      - "4200:4200"
    volumes:
      - ..:/code
    links:
      - debug_email


  celery_default:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile


  celery_thumbnails:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile


  celery_haystack:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile


  beat:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile


  debug_email:
    image: python:2.7-alpine
    command: python -m smtpd -n -c DebuggingServer 0.0.0.0:25
    ports:
      - "25"
