version: '3'

# This file is meant to be used by docker-compose to build images locally. It's useful for development.

services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx.${NGINX_MODE}.dockerfile


  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data


  memcached:
    image: memcached:alpine


  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=astrobin
      - POSTGRES_USER=astrobin
      - POSTGRES_PASSWORD=astrobin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  astrobin:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    command: bash -c "./scripts/init.sh && ./manage.py collectstatic --noinput && gunicorn wsgi:application -w 4 -b :8083 --max-requests 1000 --max-requests-jitter 50 --timeout 300 --graceful-timeout 300 -k gevent"
    ports:
      - "8083:8083"
      - "8084:8084"
      - "4200:4200"
    volumes:
      - ..:/code
    links:
      - debug_email
      - postgres
      - elasticsearch


  celery_default:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    links:
      - postgres
      - elasticsearch


  celery_thumbnails:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    links:
      - postgres
      - elasticsearch

  celery_haystack:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    links:
      - postgres
      - elasticsearch

  beat:
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    links:
      - postgres
      - elasticsearch

  debug_email:
    image: python:2.7-alpine
    command: python -m smtpd -n -c DebuggingServer 0.0.0.0:25
    ports:
      - "25"
