version: '3'

services:
  flower:
    image: ${DOCKER_REGISTRY}/astrobin-${ARCH}:${ASTROBIN_BUILD}
    command:
      - bash
      - -c
      - |
        LOCAL_STATIC_STORAGE=true python manage.py collectstatic --noinput && \
        python manage.py migrate --noinput && \
        python manage.py migrate --run-syncdb --noinput && \
        flower -A astrobin --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./astrobin.env
    environment:
      - PYTHONPATH=/usr/lib/python3/dist-packages
      - DJANGO_SETTINGS_MODULE=astrobin.settings
      - POSTGRES_DB=astrobin
      - POSTGRES_USER=astrobin
    volumes:
      - media:/media
      - tmp:/tmp
      - /astrobin-temporary-files:/astrobin-temporary-files
    deploy:
      resources:
        limits:
          memory: 2g


volumes:
  media: { }
  tmp: { }
