version: '3'

# We keep two placement groups: "app" is for the main AstroBin app, the thumbnails worker and nginx. They share the
# media volume. Everything else can go anywhere. The following service can be scaled to multiple instancesÖ
# - memcached
# - celery_*
# - astrobin
#
# Everything else should not be scaled beyond 1 or you might incur in unexpected behavior.

services:
  nginx:
    deploy:
      placement:
        constraints:
          # Must be together with the AstroBin app because they share the media directory.
          - node.labels.app == true


  rabbitmq:
    deploy:
      placement:
        constraints:
          - node.labels.default == true


  celery_default:
    deploy:
      placement:
        constraints:
          # Must be together with the AstroBin app because they share the media directory.
          - node.labels.app == true


  celery_thumbnails:
    deploy:
      placement:
        constraints:
          # Must be together with the AstroBin app because they share the media directory.
          - node.labels.app == true


  celery_haystack:
    deploy:
      placement:
        constraints:
          - node.labels.default == true

  beat:
    deploy:
      placement:
        constraints:
          - node.labels.default == true


  astrobin:
    deploy:
      placement:
        constraints:
          - node.labels.app == true


  flower:
    deploy:
      placement:
        constraints:
          - node.labels.default == true
