# Generated by Django 2.2.24 on 2021-07-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('-time',)},
        ),
    ]
