IOTD_SUBMISSION_WINDOW_DAYS = 1
IOTD_SUBMISSION_MAX_PER_DAY = 3

IOTD_REVIEW_WINDOW_DAYS = 5
IOTD_REVIEW_MAX_PER_DAY = 3

IOTD_JUDGEMENT_WINDOW_DAYS = 7
IOTD_JUDGEMENT_MAX_PER_DAY = 1
IOTD_JUDGEMENT_MAX_FUTURE_DAYS = 7
IOTD_JUDGEMENT_MAX_FUTURE_PER_JUDGE = 2

IOTD_SHOW_CHOOSING_JUDGE = False
