import os

if DEBUG or TESTING:
    STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_TEST_KEY')
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_TEST_KEY')
    STRIPE_ENDPOINT_SECRET = os.environ.get('STRIPE_ENDPOINT_SECRET_TEST')

    STRIPE_PRICE_LITE = os.environ.get('STRIPE_PRICE_TEST_LITE')
    STRIPE_PRICE_PREMIUM = os.environ.get('STRIPE_PRICE_TEST_PREMIUM')
    STRIPE_PRICE_ULTIMATE = os.environ.get('STRIPE_PRICE_TEST_ULTIMATE')
else:
    STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_LIVE_KEY')
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_LIVE_KEY')
    STRIPE_ENDPOINT_SECRET = os.environ.get('STRIPE_ENDPOINT_SECRET_LIVE')

    STRIPE_PRICE_LITE = os.environ.get('STRIPE_PRICE_LIVE_LITE')
    STRIPE_PRICE_PREMIUM = os.environ.get('STRIPE_PRICE_LIVE_PREMIUM')
    STRIPE_PRICE_ULTIMATE = os.environ.get('STRIPE_PRICE_LIVE_ULTIMATE')
