# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-07 10:50
from __future__ import unicode_literals

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToggleProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=64)),
                ('object_id', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=models.SET(common.utils.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'verbose_name': 'Toggle property',
                'verbose_name_plural': 'Toggle properties',
            },
        ),
        migrations.AlterUniqueTogether(
            name='toggleproperty',
            unique_together=set([('property_type', 'user', 'content_type', 'object_id')]),
        ),
    ]
