# Generated by Django 2.2.24 on 2023-06-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toggleproperties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toggleproperty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
