# Generated by Django 2.2.24 on 2024-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggleproperties', '0002_set_user_to_null_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toggleproperty',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
