# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-07 10:46
from __future__ import unicode_literals

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_groups', '0003_migrate_category_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(common.utils.get_sentinel_user), related_name='created_group_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='forum',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='pybb.Forum'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(common.utils.get_sentinel_user), related_name='owned_group_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
