# Generated by Django 2.2.24 on 2021-07-06 09:53

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_groups', '0003_migrate_category_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('PROFESSIONAL_NETWORK', 'Professional network'), ('CLUB_OR_ASSOCIATION', 'Club or association'), ('INTERNET_COMMUNITY', 'Internet community'), ('FRIENDS_OR_PARTNERS', 'Friends or partners'), ('GEOGRAPHICAL_AREA', 'Geographical area'), ('AD_HOC_COLLABORATION', 'Ad-hoc collaboration'), ('SPECIFIC_TO_TECHNIQUE', 'Specific to an imaging technique'), ('SPECIFIC_TO_TARGET', 'Specific to an astrophotography target'), ('SPECIFIC_TO_EQUIPMENT', 'Specific to certain equipment'), ('OTHER', 'Other')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(common.utils.get_sentinel_user), related_name='created_group_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='forum',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='pybb.Forum'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(common.utils.get_sentinel_user), related_name='owned_group_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
