# Generated by Django 2.2.24 on 2021-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_groups', '0004_add_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_image_sorting',
            field=models.CharField(choices=[('PUBLICATION', 'Publication'), ('TITLE', 'Title')], default='PUBLICATION', max_length=16, verbose_name='Default image sorting'),
        ),
    ]
