# Generated by Django 2.2.24 on 2021-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_groups', '0005_group_default_image_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_tag_sorting',
            field=models.CharField(
                blank=True,
                help_text=
                    "If images are sorted by a key/value tag, please specify which one. "
                    "<a target='_blank' href='https://welcome.astrobin.com/features/groups'>Learn more.</a>",
                max_length=16,
                null=True,
                verbose_name='Image key/value tag sorting'
            ),
        ),
        migrations.AlterField(
            model_name='group',
            name='default_image_sorting',
            field=models.CharField(
                choices=[
                    ('PUBLICATION', 'Publication'),
                    ('TITLE', 'Title'),
                    ('TAG', 'Key/value tag')
                ],
                default='PUBLICATION',
                max_length=16,
                verbose_name='Default image sorting'
            ),
        ),
    ]
