# Generated by Django 2.2.24 on 2023-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_groups', '0006_group_add_image_tag_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='forum_notice',
            field=models.TextField(
                blank=True,
                help_text="Enter a 'Forum notice' to be displayed above the 'new topic' form. Use this to communicate forum rules, disclaimers, or important information to users before they create a new post. Ensure your message is clear and concise.",
                null=True, verbose_name='Forum notice'
            ),
        ),
    ]
