from astrobin.models import *
from django.contrib import admin

admin.site.register(Gear)
admin.site.register(Telescope)
admin.site.register(Mount)
admin.site.register(Camera)
admin.site.register(FocalReducer)
admin.site.register(Software)
admin.site.register(Filter)
admin.site.register(Accessory)
admin.site.register(Subject)
admin.site.register(SubjectIdentifier)
admin.site.register(DeepSky_Acquisition)
admin.site.register(SolarSystem_Acquisition)
admin.site.register(Image)
admin.site.register(ImageRevision)
admin.site.register(Request)
admin.site.register(LocationRequest)
admin.site.register(ImageRequest)
admin.site.register(ABPOD)
admin.site.register(UserProfile)
admin.site.register(Location)
