# Generated by Django 2.2.24 on 2023-06-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pybb', '0008_increase_max_length_of_forum_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.CharField(max_length=255)),
                ('forum_slug', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='pybb.Topic')),
            ],
            options={
                'verbose_name': 'Topic redirect',
                'verbose_name_plural': 'Topic redirects',
                'ordering': ('-created_at',),
                'unique_together': {('category_slug', 'forum_slug', 'slug')},
            },
        ),
    ]
