# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_remote_source_affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesourceaffiliate',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='remote_source_affiliates'),
        ),
    ]
