# Generated by Django 2.2.24 on 2022-07-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_remote_source_affiliation', '0002_remotesourceaffiliate_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotesourceaffiliate',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
