/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.6/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_serialise_document1();
extern bool test_serialise_document2();
extern bool test_serialise_query1();
extern bool test_serialise_query2();
extern bool test_serialise_query3();
extern bool test_serialise_query4();
extern bool test_double_register_leak();
extern bool test_registry1();
extern bool test_registry2();
extern bool test_registry3();
