/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.6/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_badtransaction1();
extern bool test_committransaction1();
extern bool test_canceltransaction1();
extern bool test_canceltransaction2();
