/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.6/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_valuestream1();
extern bool test_valuestream2();
extern bool test_valuestream3();
extern bool test_valueweightsource5();
extern bool test_valuemapsource1();
extern bool test_valuemapsource2();
extern bool test_fixedweightsource2();
extern bool test_decvalwtsource1();
extern bool test_decvalwtsource2();
extern bool test_decvalwtsource3();
extern bool test_decvalwtsource4();
extern bool test_decvalwtsource5();
