/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.6/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_valuestats1();
extern bool test_valuestats2();
extern bool test_valuestats3();
extern bool test_valuestats4();
extern bool test_valuestats5();
