class GroupName:
    IOTD_STAFF = 'iotd_staff'
    IOTD_SUBMITTERS = 'iotd_submitters'
    IOTD_REVIEWERS = 'iotd_reviewers'
    IOTD_JUDGES = 'iotd_judges'
    OWN_EQUIPMENT_MIGRATORS = 'own_equipment_migrators'
    GLOBAL_EQUIPMENT_MIGRATORS = 'global_equipment_migrators'
    EQUIPMENT_MODERATORS = 'equipment_moderators'
    BETA_TESTERS = 'AstroBin Beta Testers'
    MARKETPLACE_MODERATORS = 'marketplace_moderators'
