# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentretailer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentretailer',
            name='website',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentbrandlisting',
            unique_together=set([('brand', 'retailer')]),
        ),
    ]
