# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbrandretailer',
            name='countries',
            field=models.CharField(default='us', max_length=120),
            preserve_default=False,
        ),
    ]
