# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='subcategory',
            field=models.CharField(choices=[(b'OPTICAL_TELESCOPE', 'Telescope'), (b'OPTICAL_CAMERA_LENS', 'Camera lens'), (b'OPTICAL_FOCAL_REDUCER', 'Focal reducer'), (b'OPTICAL_DIAGONAL', 'Diagonal'), (b'OPTICAL_FIELD_CORRECTOR', 'Field corrector'), (b'OPTICAL_EYEPIECE', 'Eyepiece'), (b'OPTICAL_FILTER_L', 'Luminance filter'), (b'OPTICAL_FILTER_R', 'Red filter'), (b'OPTICAL_FILTER_G', 'Green filter'), (b'OPTICAL_FILTER_B', 'Blue filter'), (b'OPTICAL_FILTER_HA', 'Hydrogen Alpha filter'), (b'OPTICAL_FILTER_SII', 'Sulfur II filter'), (b'OPTICAL_FILTER_OIII', 'Oxygen III filter'), (b'OPTICAL_FILTER_LP', 'Light pollution filter'), (b'OPTICAL_FILTER_SOLAR', 'Solar filter'), (b'OPTICAL_FILTER_LUNAR', 'Lunar filter'), (b'DETECTOR_DEDICATED', 'Dedicated astronomical camera'), (b'DETECTOR_DSLR', 'DSLR camera'), (b'DETECTOR_MIRRORLESS', 'Mirrorless camera'), (b'DETECTOR_FILM', 'Film camera'), (b'DETECTOR_GUIDER', 'Guide camera'), (b'TRACKER_EQ_MOUNT', 'Equatorial mount'), (b'TRACKER_ALTAZ_MOUNT', 'Alt-azimuth mount'), (b'TRACKER_BARN_DOOR', 'Barn door tracker'), (b'TRACKER_TRIPOD', 'Tripod'), (b'TRACKER_PIER', 'Pier'), (b'ACCESSORY_ADAPTER', 'Adapter'), (b'ACCESSORY_FOCUS_MASK', 'Focus mask'), (b'ACCESSORY_FOCUSER', 'Focuser'), (b'ACCESSORY_ARTIFICIAL_FLAT_FIELD', 'Artificial flat field'), (b'ACCESSORY_DEW_CONTROL', 'Dew control'), (b'ACCESSORY_FILTER_WHEEL', 'Filter wheel'), (b'ACCESSORY_INTERVALOMETER', 'Intervalometer'), (b'ACCESSORY_WEATHER_STATION', 'Weather station'), (b'SOFTWARE_OBSERVATORY_CONTROL', 'Observatory control'), (b'SOFTWARE_DATA_ACQUISITION', 'Data acquisition'), (b'SOFTWARE_DATA_PROCESSING', 'Data processing')], help_text='The subcategory that best defines this item.', max_length=64, verbose_name='Subcategory'),
        ),
    ]
