# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbrandlisting',
            name='url_de',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='url_de',
            field=models.URLField(blank=True, null=True),
        ),
    ]
