# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-04 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0002_add_uniqueness_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItemListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_item_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='equipmentbrand',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentbrandlisting',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_brand_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentretailer',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_retailers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrobin_apps_equipment.EquipmentRetailer'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemlisting',
            unique_together=set([('name', 'retailer')]),
        ),
    ]
