# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0002_equipmentbrandretailer_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrandretailer',
            name='countries',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
