# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-23 10:56
from __future__ import unicode_literals

import astrobin_apps_equipment.models.equipment_item
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0004_add_equipmentbrand_website_and_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('type', models.CharField(choices=[(b'CCD', 'CCD'), (b'CMOS', 'CMOS'), (b'DSLR', 'DSLR'), (b'GUIDER/PLANETARY', 'Guider/Planetary'), (b'FILM', 'Film'), (b'COMPACT', 'Compact'), (b'VIDEO', 'Video camera')], max_length=64)),
                ('cooled', models.BooleanField(default=False)),
                ('max_cooling', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('back_focus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_cameras', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_cameras_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('quantum_efficiency', models.DecimalField(decimal_places=2, help_text=b'%', max_digits=5, null=True)),
                ('pixel_size', models.DecimalField(blank=True, decimal_places=2, help_text=b'&mu;m', max_digits=6, null=True)),
                ('pixel_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pixel_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sensor_width', models.DecimalField(blank=True, decimal_places=2, help_text=b'mm', max_digits=6, null=True)),
                ('sensor_height', models.DecimalField(blank=True, decimal_places=2, help_text=b'mm', max_digits=6, null=True)),
                ('full_well_capacity', models.PositiveIntegerField(blank=True, help_text=b'e-', null=True)),
                ('read_noise', models.DecimalField(blank=True, decimal_places=2, help_text=b'e', max_digits=6, null=True)),
                ('frame_rate', models.PositiveSmallIntegerField(blank=True, help_text=b'FPS', null=True)),
                ('adc', models.PositiveSmallIntegerField(blank=True, help_text=b'bit', null=True)),
                ('color_or_mono', models.CharField(blank=True, choices=[(b'C', 'Color'), (b'M', 'Monochromatic')], max_length=1, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_sensors', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_sensors_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='astrobin_apps_equipment.Sensor'),
        ),
    ]
