# Generated by Django 2.2.24 on 2021-07-29 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import astrobin_apps_equipment.models.equipment_item


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0006_auto_20210729_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('type', models.CharField(
                    choices=[('REFR ACHRO', 'Refractor: achromatic'), ('REFR SEMI-APO', 'Refractor: semi-apochromatic'),
                             ('REFR APO', 'Refractor: apochromatic'),
                             ('REFR NON-ACHRO GALILEAN', 'Refractor: non-achromatic Galilean'),
                             ('REFR NON-ACHRO KEPLERIAN', 'Refractor: non-achromatic Keplerian'),
                             ('REFR SUPERACHRO', 'Refractor: superachromat'),
                             ('REFL DALL-KIRKHAM', 'Reflector: Dall-Kirkham'), ('REFL NASMYTH', 'Reflector: Nasmyth'),
                             ('REFL RITCHEY CHRETIEN', 'Reflector: Ritchey Chretien'),
                             ('REFL GREGORIAN', 'Reflector: Gregorian'),
                             ('REFL HERSCHELLIAN', 'Reflector: Herschellian'),
                             ('REFL NEWTONIAN', 'Reflector: Newtonian'),
                             ('CATA ARGUNOV-CASSEGRAIN', 'Catadioptric: Argunov-Cassegrain'),
                             ('CATA KLEVTSOV-CASSEGRAIN', 'Catadioptric: Klevtsov-Cassegrain'),
                             ('CATA LURIE-HOUGHTON', 'Catadioptric: Lurie-Houghton'),
                             ('CATA MAKSUTOV', 'Catadioptric: Maksutov'),
                             ('CATA MAKSUTOV-CASSEGRAIN', 'Catadioptric: Maksutov-Cassegrain'),
                             ('CATA MOD DALL-KIRKHAM', 'Catadioptric: modified Dall-Kirkham'),
                             ('CATA SCHMIDT CAMERA', 'Catadioptric: Schmidt camera'),
                             ('CATA SCHMIDT-CASSEGRAIN', 'Catadioptric: Schmidt-Cassegrain'),
                             ('CATA ACF SCHMIDT-CASSEGRAIN', 'Catadioptric: ACF Schmidt-Cassegrain'),
                             ('CATA ROWE-ACKERMANN SCHMIDT', 'Catadioptric: Rowe-Atkinson Schmidt astrograph'),
                             ('CAMERA LENS', 'Camera lens'), ('BINOCULARS', 'Binoculars')], max_length=64,
                    verbose_name='Type')),
                ('min_aperture', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True,
                                                     verbose_name='Min. aperture (mm)')),
                ('max_aperture', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True,
                                                     verbose_name='Max. aperture (mm)')),
                ('min_focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True,
                                                         verbose_name='Min. focal length (mm)')),
                ('max_focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True,
                                                         verbose_name='Max. focal length (mm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True,
                                               verbose_name='Weight (kg)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            related_name='astrobin_apps_equipment_telescopes',
                                            to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by',
                 models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='astrobin_apps_equipment_telescopes_created',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'abstract': False,
            },
        ),
    ]
