# Generated by Django 2.2.24 on 2021-09-03 20:41

import astrobin_apps_equipment.models.equipment_item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0008_alter_camera_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path),
        ),
    ]
