# Generated by Django 2.2.24 on 2021-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0010_make_item_brand_and_name_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
