# Generated by Django 2.2.24 on 2021-09-14 08:14

import astrobin_apps_equipment.models.equipment_item
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0014_add_reviewer_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_cameras', to='astrobin_apps_equipment.EquipmentBrand'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_sensor_cameras', to='astrobin_apps_equipment.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_sensors', to='astrobin_apps_equipment.EquipmentBrand'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_telescopes', to='astrobin_apps_equipment.EquipmentBrand'),
        ),
        migrations.CreateModel(
            name='CameraEditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('reviewed_timestamp', models.DateTimeField(editable=False, null=True)),
                ('reviewer_decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], editable=False, max_length=8, null=True)),
                ('reviewer_rejection_reason', models.CharField(choices=[('TYPO', "There's a typo in the name of the item"), ('WRONG_BRAND', 'The item was assigned to the wrong brand'), ('INACCURATE_DATA', 'Some data is inaccurate'), ('INSUFFICIENT_DATA', 'Some important data is missing'), ('OTHER', 'Other')], editable=False, max_length=32, null=True)),
                ('reviewer_comment', models.TextField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('type', models.CharField(choices=[('DEDICATED_DEEP_SKY', 'Dedicated deep-sky camera'), ('DSLR_MIRRORLESS', 'General purpose DSLR or mirrorless camera'), ('GUIDER_PLANETARY', 'Guider/Planetary camera'), ('VIDEO', 'General purpose video camera'), ('FILM', 'Film camera'), ('OTHER', 'Other')], max_length=64, verbose_name='Type')),
                ('cooled', models.BooleanField(default=False)),
                ('max_cooling', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('back_focus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edit_proposal_created', models.DateTimeField(auto_now_add=True)),
                ('edit_proposal_updated', models.DateTimeField(auto_now=True)),
                ('edit_proposal_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_timestamp', models.DateTimeField(editable=False, null=True)),
                ('edit_proposal_review_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_review_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_status', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=8, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_cameraeditproposals', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_cameraeditproposals_created', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_cameraeditproposal_edit_proposals', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_cameraeditproposal_edit_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='astrobin_apps_equipment.Camera')),
                ('reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_cameraeditproposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_sensor_cameraeditproposals', to='astrobin_apps_equipment.Sensor')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'abstract': False,
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
