# Generated by Django 2.2.24 on 2021-09-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0015_add_camera_edit_proposal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cameraeditproposal',
            unique_together=set(),
        ),
    ]
