# Generated by Django 2.2.24 on 2021-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0016_remove_unique_together_from_camera_edit_proposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraeditproposal',
            options={'ordering': ['created']},
        ),
    ]
