# Generated by Django 2.2.24 on 2021-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0017_add_sorting_to_camera_edit_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraeditproposal',
            name='edit_proposal_review_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'),
                                                        ('SUPERSEDED', 'Superseded')], max_length=10, null=True),
        ),
    ]
