# Generated by Django 2.2.24 on 2021-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0018_add_superseded_review_status_to_camera_edit_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraeditproposal',
            name='edit_proposal_original_properties',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
