# Generated by Django 2.2.24 on 2021-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0019_cameraeditproposal_edit_proposal_original_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='reviewer_decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False,
                                   max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cameraeditproposal',
            name='edit_proposal_review_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'),
                                                        ('SUPERSEDED', 'Superseded')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cameraeditproposal',
            name='reviewer_decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False,
                                   max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='reviewer_decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False,
                                   max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='reviewer_decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False,
                                   max_length=8, null=True),
        ),
    ]
