# Generated by Django 2.2.24 on 2021-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0021_alter_camera_and_telescope_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telescope',
            name='max_aperture',
        ),
        migrations.RemoveField(
            model_name='telescope',
            name='min_aperture',
        ),
        migrations.AddField(
            model_name='telescope',
            name='aperture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Aperture (mm)'),
        ),
    ]
