# Generated by Django 2.2.24 on 2021-10-07 13:54

import astrobin_apps_equipment.models.equipment_item
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0022_remove_double_telescope_aperture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelescopeEditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('reviewed_timestamp', models.DateTimeField(editable=False, null=True)),
                ('reviewer_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False, max_length=8, null=True)),
                ('reviewer_rejection_reason', models.CharField(choices=[('TYPO', "There's a typo in the name of the item"), ('WRONG_BRAND', 'The item was assigned to the wrong brand'), ('INACCURATE_DATA', 'Some data is inaccurate'), ('INSUFFICIENT_DATA', 'Some important data is missing'), ('OTHER', 'Other')], editable=False, max_length=32, null=True)),
                ('reviewer_comment', models.TextField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('edit_proposal_original_properties', models.TextField()),
                ('edit_proposal_created', models.DateTimeField(auto_now_add=True)),
                ('edit_proposal_updated', models.DateTimeField(auto_now=True)),
                ('edit_proposal_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_timestamp', models.DateTimeField(editable=False, null=True)),
                ('edit_proposal_review_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_review_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_status', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], max_length=10, null=True)),
                ('type', models.CharField(choices=[('REFRACTOR_ACHROMATIC', 'Refractor: achromatic'), ('REFRACTOR_SEMI_APOCHROMATIC', 'Refractor: semi-apochromatic'), ('REFRACTOR_APOCHROMATIC', 'Refractor: apochromatic'), ('REFRACTOR_NON_ACHROMATIC_GALILEAN', 'Refractor: non-achromatic Galilean'), ('REFRACTOR_NON_ACHROMATIC_KEPLERIAN', 'Refractor: non-achromatic Keplerian'), ('REFRACTOR_SUPERACHROMAT', 'Refractor: superachromat'), ('REFLECTOR_DALL_KIRKHAM', 'Reflector: Dall-Kirkham'), ('REFLECTOR_NASMYTH', 'Reflector: Nasmyth'), ('REFLECTOR_RITCHEY_CHRETIEN', 'Reflector: Ritchey Chretien'), ('REFLECTOR_GREGORIAN', 'Reflector: Gregorian'), ('REFLECTOR_HERSCHELLIAN', 'Reflector: Herschellian'), ('REFLECTOR_NEWTONIAN', 'Reflector: Newtonian'), ('CATADIOPTRIC_ARGUNOV_CASSEGRAIN', 'Catadioptric: Argunov-Cassegrain'), ('CATADIOPTRIC_KLEVTSOV_CASSEGRAIN', 'Catadioptric: Klevtsov-Cassegrain'), ('CATADIOPTRIC_LURIE_HOUGHTON', 'Catadioptric: Lurie-Houghton'), ('CATADIOPTRIC_MAKSUTOV', 'Catadioptric: Maksutov'), ('CATADIOPTRIC_MAKSUTOV_CASSEGRAIN', 'Catadioptric: Maksutov-Cassegrain'), ('CATADIOPTRIC_MAKSUTOV_CASSEGRAIN', 'Catadioptric: modified Dall-Kirkham'), ('CATADIOPTRIC_MODIFIED_DALL_KIRKHAM', 'Catadioptric: Schmidt camera'), ('CATADIOPTRIC_SCHMIDT_CASSEGRAIN', 'Catadioptric: Schmidt-Cassegrain'), ('CATADIOPTRIC_ACF_SCHMIDT_CASSEGRAIN', 'Catadioptric: ACF Schmidt-Cassegrain'), ('CATADIOPTRIC_ROWE_ACKERMAN_SCHMIDT', 'Catadioptric: Rowe-Atkinson Schmidt astrograph'), ('CAMERA_LENS', 'Camera lens'), ('BINOCULARS', 'Binoculars')], max_length=64, verbose_name='Type')),
                ('aperture', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Aperture (mm)')),
                ('min_focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Min. focal length (mm)')),
                ('max_focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max. focal length (mm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_telescopeeditproposals', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_telescopeeditproposals_created', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_telescopeeditproposal_edit_proposals', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_telescopeeditproposal_edit_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='astrobin_apps_equipment.Telescope')),
                ('reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_telescopeeditproposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
