# Generated by Django 2.2.24 on 2021-10-14 20:17

import astrobin_apps_equipment.models.equipment_item
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0023_telescopeeditproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorEditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('reviewed_timestamp', models.DateTimeField(editable=False, null=True)),
                ('reviewer_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False, max_length=8, null=True)),
                ('reviewer_rejection_reason', models.CharField(choices=[('TYPO', "There's a typo in the name of the item"), ('WRONG_BRAND', 'The item was assigned to the wrong brand'), ('INACCURATE_DATA', 'Some data is inaccurate'), ('INSUFFICIENT_DATA', 'Some important data is missing'), ('OTHER', 'Other')], editable=False, max_length=32, null=True)),
                ('reviewer_comment', models.TextField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('quantum_efficiency', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pixel_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pixel_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pixel_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sensor_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sensor_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('full_well_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('read_noise', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('frame_rate', models.PositiveSmallIntegerField(blank=True, help_text='FPS', null=True, verbose_name='Frame rate')),
                ('adc', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color_or_mono', models.CharField(blank=True, choices=[('C', 'Color'), ('M', 'Monochromatic')], max_length=1, null=True)),
                ('edit_proposal_original_properties', models.TextField()),
                ('edit_proposal_created', models.DateTimeField(auto_now_add=True)),
                ('edit_proposal_updated', models.DateTimeField(auto_now=True)),
                ('edit_proposal_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_timestamp', models.DateTimeField(editable=False, null=True)),
                ('edit_proposal_review_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_review_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_status', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], max_length=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_sensoreditproposals', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_sensoreditproposals_created', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_sensoreditproposal_edit_proposals', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_sensoreditproposal_edit_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='astrobin_apps_equipment.Sensor')),
                ('reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_sensoreditproposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
