# Generated by Django 2.2.24 on 2021-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0024_sensoreditproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='quantum_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensoreditproposal',
            name='quantum_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
