# Generated by Django 2.2.24 on 2021-11-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0025_alter_sensor_quantum_efficiency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraeditproposal',
            options={'ordering': ['-edit_proposal_created']},
        ),
        migrations.AlterModelOptions(
            name='sensoreditproposal',
            options={'ordering': ['-edit_proposal_created']},
        ),
        migrations.AlterModelOptions(
            name='telescopeeditproposal',
            options={'ordering': ['-edit_proposal_created']},
        ),
    ]
