# Generated by Django 2.2.24 on 2021-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0026_add_edit_proposal_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='modified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('brand', 'name', 'modified')},
        ),
    ]
