# Generated by Django 2.2.24 on 2021-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0027_add_camera_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraeditproposal',
            name='create_modified_variant',
            field=models.BooleanField(default=False),
        ),
    ]
