# Generated by Django 2.2.24 on 2021-11-10 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0028_cameraeditproposal_create_modified_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['brand__name', 'name', 'modified']},
        ),
    ]
