# Generated by Django 2.2.24 on 2021-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0029_add_modified_to_camera_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='specification_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='specification_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
