# Generated by Django 2.2.24 on 2021-11-15 11:25

import astrobin_apps_equipment.models.equipment_item
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0032_mount_alter_type_to_fix_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('reviewed_timestamp', models.DateTimeField(editable=False, null=True)),
                ('reviewer_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False, max_length=8, null=True)),
                ('reviewer_rejection_reason', models.CharField(choices=[('TYPO', "There's a typo in the name of the item"), ('WRONG_BRAND', 'The item was assigned to the wrong brand'), ('INACCURATE_DATA', 'Some data is inaccurate'), ('INSUFFICIENT_DATA', 'Some important data is missing'), ('OTHER', 'Other')], editable=False, max_length=32, null=True)),
                ('reviewer_comment', models.TextField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('type', models.CharField(choices=[('H_ALPHA', 'Hydrogen-alpha (Hα)'), ('H_BETA', 'Hydrogen-beta (Hβ)'), ('SII', 'Sulfur-II (SII)'), ('OIII', 'Oxygen-III (OIII)'), ('NII', 'Nitrogen-II (NII)'), ('UV', 'Ultraviolet (UV)'), ('IR', 'Infrared (IR)'), ('MULTIBAND', 'Multiband'), ('LP', 'Light pollution suppression'), ('L', 'Luminance/clear (L)'), ('R', 'Red channel (R)'), ('G', 'Green channel (G)'), ('B', 'Blue channel (B)'), ('ND', 'Neutral density (ND)'), ('UHC', 'Ultra High Contrast (UHC)'), ('SKY_GLOW', 'Sky glow'), ('SOLAR', 'Solar'), ('LUNAR', 'Lunar'), ('COMETARY', 'Cometary'), ('PHOTOMETRIC_U', 'Photometric Ultraviolet'), ('PHOTOMETRIC_B', 'Photometric Blue'), ('PHOTOMETRIC_V', 'Photometric Visual'), ('PHOTOMETRIC_R', 'Photometric Red'), ('PHOTOMETRIC_I', 'Photometric Infrared'), ('OTHER', 'Other')], max_length=16, verbose_name='Type')),
                ('bandwidth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bandwidth (nm)')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Size (mm)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_filters', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_filters_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_filters_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'abstract': False,
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FilterEditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('reviewed_timestamp', models.DateTimeField(editable=False, null=True)),
                ('reviewer_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], editable=False, max_length=8, null=True)),
                ('reviewer_rejection_reason', models.CharField(choices=[('TYPO', "There's a typo in the name of the item"), ('WRONG_BRAND', 'The item was assigned to the wrong brand'), ('INACCURATE_DATA', 'Some data is inaccurate'), ('INSUFFICIENT_DATA', 'Some important data is missing'), ('OTHER', 'Other')], editable=False, max_length=32, null=True)),
                ('reviewer_comment', models.TextField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_item.image_upload_path)),
                ('edit_proposal_original_properties', models.TextField()),
                ('edit_proposal_created', models.DateTimeField(auto_now_add=True)),
                ('edit_proposal_updated', models.DateTimeField(auto_now=True)),
                ('edit_proposal_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_timestamp', models.DateTimeField(editable=False, null=True)),
                ('edit_proposal_review_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('edit_proposal_review_comment', models.TextField(blank=True, null=True)),
                ('edit_proposal_review_status', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], max_length=10, null=True)),
                ('type', models.CharField(choices=[('H_ALPHA', 'Hydrogen-alpha (Hα)'), ('H_BETA', 'Hydrogen-beta (Hβ)'), ('SII', 'Sulfur-II (SII)'), ('OIII', 'Oxygen-III (OIII)'), ('NII', 'Nitrogen-II (NII)'), ('UV', 'Ultraviolet (UV)'), ('IR', 'Infrared (IR)'), ('MULTIBAND', 'Multiband'), ('LP', 'Light pollution suppression'), ('L', 'Luminance/clear (L)'), ('R', 'Red channel (R)'), ('G', 'Green channel (G)'), ('B', 'Blue channel (B)'), ('ND', 'Neutral density (ND)'), ('UHC', 'Ultra High Contrast (UHC)'), ('SKY_GLOW', 'Sky glow'), ('SOLAR', 'Solar'), ('LUNAR', 'Lunar'), ('COMETARY', 'Cometary'), ('PHOTOMETRIC_U', 'Photometric Ultraviolet'), ('PHOTOMETRIC_B', 'Photometric Blue'), ('PHOTOMETRIC_V', 'Photometric Visual'), ('PHOTOMETRIC_R', 'Photometric Red'), ('PHOTOMETRIC_I', 'Photometric Infrared'), ('OTHER', 'Other')], max_length=16, verbose_name='Type')),
                ('bandwidth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bandwidth (nm)')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Size (mm)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrobin_apps_equipment_brand_filtereditproposals', to='astrobin_apps_equipment.EquipmentBrand')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_filtereditproposals_created', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_filtereditproposal_edit_proposals', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_filtereditproposal_edit_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('edit_proposal_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='astrobin_apps_equipment.Filter')),
                ('reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrobin_apps_equipment_filtereditproposals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edit_proposal_created'],
                'abstract': False,
            },
        ),
    ]
