# Generated by Django 2.2.24 on 2021-11-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0034_accessory_accessoryeditproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
    ]
