# Generated by Django 2.2.24 on 2021-11-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0037_migrate_sensor_specification_url_to_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='specification_url',
        ),
        migrations.RemoveField(
            model_name='sensoreditproposal',
            name='specification_url',
        ),
    ]
