# Generated by Django 2.2.24 on 2021-12-04 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0042_fix_telescope_types_mistakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remote_source', models.CharField(blank=True, max_length=8, null=True, verbose_name='Remote data source')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('accessories', models.ManyToManyField(blank=True, related_name='presets_using', to='astrobin_apps_equipment.Accessory', verbose_name='Accessories')),
                ('filters', models.ManyToManyField(blank=True, related_name='presets_using', to='astrobin_apps_equipment.Filter', verbose_name='Filters')),
                ('guiding_cameras', models.ManyToManyField(blank=True, related_name='presets_using_for_guiding', to='astrobin_apps_equipment.Camera', verbose_name='Guiding cameras')),
                ('guiding_telescopes', models.ManyToManyField(blank=True, related_name='presets_using_for_guiding', to='astrobin_apps_equipment.Telescope', verbose_name='Guiding telescopes or lenses')),
                ('imaging_cameras', models.ManyToManyField(blank=True, related_name='presets_using_for_imaging', to='astrobin_apps_equipment.Camera', verbose_name='Imaging cameras')),
                ('imaging_telescopes', models.ManyToManyField(blank=True, related_name='presets_using_for_imaging', to='astrobin_apps_equipment.Telescope', verbose_name='Imaging telescopes or lenses')),
                ('mounts', models.ManyToManyField(blank=True, related_name='presets_using', to='astrobin_apps_equipment.Mount', verbose_name='Mounts')),
                ('software', models.ManyToManyField(blank=True, related_name='presets_using', to='astrobin_apps_equipment.Software', verbose_name='Software')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'user')},
            },
        ),
    ]
