# Generated by Django 2.2.24 on 2022-04-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0044_add_item_reviewer_rejection_reason_DUPLICATE'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrandlisting',
            name='brand',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='listings',
                to='astrobin_apps_equipment.EquipmentBrand'
            ),
        ),
    ]
