# Generated by Django 2.2.24 on 2022-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0046_add_some_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(
                choices=[('H_ALPHA', 'Hydrogen-alpha (Hα)'), ('H_BETA', 'Hydrogen-beta (Hβ)'),
                         ('SII', 'Sulfur-II (SII)'), ('OIII', 'Oxygen-III (OIII)'), ('NII', 'Nitrogen-II (NII)'),
                         ('UV', 'Ultraviolet (UV)'), ('IR', 'Infrared (IR)'), ('MULTIBAND', 'Multiband'),
                         ('LP', 'Light pollution suppression'), ('L', 'Luminance/clear (L)'), ('R', 'Red channel (R)'),
                         ('G', 'Green channel (G)'), ('B', 'Blue channel (B)'), ('ND', 'Neutral density (ND)'),
                         ('UHC', 'Ultra High Contrast (UHC)'), ('SKY_GLOW', 'Sky glow'), ('SOLAR', 'Solar'),
                         ('LUNAR', 'Lunar'), ('PLANETARY', 'Planetary'), ('COMETARY', 'Cometary'),
                         ('PHOTOMETRIC_U', 'Photometric Ultraviolet'), ('PHOTOMETRIC_B', 'Photometric Blue'),
                         ('PHOTOMETRIC_V', 'Photometric Visual'), ('PHOTOMETRIC_R', 'Photometric Red'),
                         ('PHOTOMETRIC_I', 'Photometric Infrared'), ('OTHER', 'Other')], max_length=16,
                verbose_name='Type'
            ),
        ),
        migrations.AlterField(
            model_name='filtereditproposal',
            name='type',
            field=models.CharField(
                choices=[('H_ALPHA', 'Hydrogen-alpha (Hα)'), ('H_BETA', 'Hydrogen-beta (Hβ)'),
                         ('SII', 'Sulfur-II (SII)'), ('OIII', 'Oxygen-III (OIII)'), ('NII', 'Nitrogen-II (NII)'),
                         ('UV', 'Ultraviolet (UV)'), ('IR', 'Infrared (IR)'), ('MULTIBAND', 'Multiband'),
                         ('LP', 'Light pollution suppression'), ('L', 'Luminance/clear (L)'), ('R', 'Red channel (R)'),
                         ('G', 'Green channel (G)'), ('B', 'Blue channel (B)'), ('ND', 'Neutral density (ND)'),
                         ('UHC', 'Ultra High Contrast (UHC)'), ('SKY_GLOW', 'Sky glow'), ('SOLAR', 'Solar'),
                         ('LUNAR', 'Lunar'), ('PLANETARY', 'Planetary'), ('COMETARY', 'Cometary'),
                         ('PHOTOMETRIC_U', 'Photometric Ultraviolet'), ('PHOTOMETRIC_B', 'Photometric Blue'),
                         ('PHOTOMETRIC_V', 'Photometric Visual'), ('PHOTOMETRIC_R', 'Photometric Red'),
                         ('PHOTOMETRIC_I', 'Photometric Infrared'), ('OTHER', 'Other')], max_length=16,
                verbose_name='Type'
            ),
        ),
    ]
