# Generated by Django 2.2.24 on 2022-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0050_fix_filter_size_EOS_APS_C'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='size',
            field=models.CharField(
                blank=True,
                choices=[('ROUND_1_25_IN', 'Round 1.25"'), ('ROUND_2_IN', 'Round 2"'), ('ROUND_27_MM', 'Round 27 mm'),
                         ('ROUND_31_MM', 'Round 31 mm'), ('ROUND_36_MM', 'Round 36 mm"'),
                         ('ROUND_42_MM', 'Round 42 mm"'), ('ROUND_46_MM', 'Round 46 mm"'),
                         ('ROUND_50_MM', 'Round 50 mm"'), ('ROUND_52_MM', 'Round 52 mm"'),
                         ('ROUND_62_MM', 'Round 62 mm"'), ('ROUND_65_MM', 'Round 65 mm"'),
                         ('ROUND_67_MM', 'Round 67 mm"'), ('ROUND_72_MM', 'Round 72 mm"'),
                         ('ROUND_77_MM', 'Round 77 mm"'), ('ROUND_82_MM', 'Round 82 mm"'),
                         ('SQUARE_50_MM', 'Square 50x50 mm'), ('SQUARE_65_MM', 'Square 65x65 mm'),
                         ('SQUARE_100_MM', 'Square 100x100 mm'), ('RECT_101_143_MM', 'Rectangular 101x143 mm'),
                         ('EOS_APS_C', 'EOS APS-C'), ('EOS_FULL', 'EOS Full'), ('EOS_M', 'EOS M'), ('EOS_R', 'EOS R'),
                         ('SONY', 'Sony'), ('SONY_FULL', 'Sony Full'), ('NIKON', 'Nikon'), ('NIKON_Z', 'Nikon Z'),
                         ('NIKON_FULL', 'Nikon Full'), ('PENTAX', 'Pentax'),
                         ('T_THREAD_CELL_M42', 'T-thread cell (M42 x 0.75)'), ('M52', 'M52'), ('SCT', 'SCT'),
                         ('OTHER', 'Other')], max_length=32, null=True, verbose_name='Size'
            ),
        ),
        migrations.AlterField(
            model_name='filtereditproposal',
            name='size',
            field=models.CharField(
                blank=True,
                choices=[('ROUND_1_25_IN', 'Round 1.25"'), ('ROUND_2_IN', 'Round 2"'), ('ROUND_27_MM', 'Round 27 mm'),
                         ('ROUND_31_MM', 'Round 31 mm'), ('ROUND_36_MM', 'Round 36 mm"'),
                         ('ROUND_42_MM', 'Round 42 mm"'), ('ROUND_46_MM', 'Round 46 mm"'),
                         ('ROUND_50_MM', 'Round 50 mm"'), ('ROUND_52_MM', 'Round 52 mm"'),
                         ('ROUND_62_MM', 'Round 62 mm"'), ('ROUND_65_MM', 'Round 65 mm"'),
                         ('ROUND_67_MM', 'Round 67 mm"'), ('ROUND_72_MM', 'Round 72 mm"'),
                         ('ROUND_77_MM', 'Round 77 mm"'), ('ROUND_82_MM', 'Round 82 mm"'),
                         ('SQUARE_50_MM', 'Square 50x50 mm'), ('SQUARE_65_MM', 'Square 65x65 mm'),
                         ('SQUARE_100_MM', 'Square 100x100 mm'), ('RECT_101_143_MM', 'Rectangular 101x143 mm'),
                         ('EOS_APS_C', 'EOS APS-C'), ('EOS_FULL', 'EOS Full'), ('EOS_M', 'EOS M'), ('EOS_R', 'EOS R'),
                         ('SONY', 'Sony'), ('SONY_FULL', 'Sony Full'), ('NIKON', 'Nikon'), ('NIKON_Z', 'Nikon Z'),
                         ('NIKON_FULL', 'Nikon Full'), ('PENTAX', 'Pentax'),
                         ('T_THREAD_CELL_M42', 'T-thread cell (M42 x 0.75)'), ('M52', 'M52'), ('SCT', 'SCT'),
                         ('OTHER', 'Other')], max_length=32, null=True, verbose_name='Size'
            ),
        ),
    ]
