# Generated by Django 2.2.24 on 2022-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0057_add_telescope_type_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='mount',
            name='max_payload',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Payload (kg)'),
        ),
        migrations.AlterField(
            model_name='mounteditproposal',
            name='max_payload',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Payload (kg)'),
        ),
    ]
