# Generated by Django 2.2.24 on 2022-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0059_add_mount_type_tripod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='type',
            field=models.CharField(
                choices=[('ALTAZIMUTH', 'Alt-Az (altazimuth)'), ('WEDGED_ALTAZIMUTH', 'Wedged Alt-Az'),
                         ('EQUATORIAL', 'Equatorial'), ('GERMAN_EQUATORIAL', 'German equatorial'), ('FORK', 'Fork'),
                         ('DOBSONIAN', 'Dobsonian'), ('PORTABLE_ENGLISH', 'Portable English'),
                         ('BARN_DOOR_TRACKER', 'Star tracker'), ('ALT_ALT', 'Alt-Alt (altitude-altitude)'),
                         ('TRANSIT', 'Transit'), ('HEXAPOD', 'Hexapod'), ('TRIPOD', 'Tripod'),
                         ('DUAL_ALT_AZ_EQ', 'Dual Alt-Az / Equatorial'), ('OTHER', 'Other')], max_length=32,
                verbose_name='Type'
            ),
        ),
        migrations.AlterField(
            model_name='mounteditproposal',
            name='type',
            field=models.CharField(
                choices=[('ALTAZIMUTH', 'Alt-Az (altazimuth)'), ('WEDGED_ALTAZIMUTH', 'Wedged Alt-Az'),
                         ('EQUATORIAL', 'Equatorial'), ('GERMAN_EQUATORIAL', 'German equatorial'), ('FORK', 'Fork'),
                         ('DOBSONIAN', 'Dobsonian'), ('PORTABLE_ENGLISH', 'Portable English'),
                         ('BARN_DOOR_TRACKER', 'Star tracker'), ('ALT_ALT', 'Alt-Alt (altitude-altitude)'),
                         ('TRANSIT', 'Transit'), ('HEXAPOD', 'Hexapod'), ('TRIPOD', 'Tripod'),
                         ('DUAL_ALT_AZ_EQ', 'Dual Alt-Az / Equatorial'), ('OTHER', 'Other')], max_length=32,
                verbose_name='Type'
            ),
        ),
    ]
