# Generated by Django 2.2.24 on 2022-05-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0060_add_mount_type_dual_altaz_eq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mount',
            name='tracking_accuracy',
        ),
        migrations.RemoveField(
            model_name='mounteditproposal',
            name='tracking_accuracy',
        ),
        migrations.AddField(
            model_name='mount',
            name='periodic_error',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Periodic error (arcsec)'
            ),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='periodic_error',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Periodic error (arcsec)'
            ),
        ),
    ]
