# Generated by Django 2.2.24 on 2022-05-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0062_fix_value_of_mount_type_star_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cooled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cooled'),
        ),
        migrations.AlterField(
            model_name='cameraeditproposal',
            name='cooled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cooled'),
        ),
    ]
