# Generated by Django 2.2.24 on 2022-05-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0063_make_camera_cooled_field_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelescopeMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usage_type', models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.Telescope')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='telescopemigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_to', to='astrobin_apps_equipment.Telescope')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.Software')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='softwaremigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_to', to='astrobin_apps_equipment.Software')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MountMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.Mount')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mountmigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_to', to='astrobin_apps_equipment.Mount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocalReducerMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.FocalReducer')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='focalreducermigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_from_focal_reducers_as_to', to='astrobin_apps_equipment.Accessory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.Filter')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='filtermigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_to', to='astrobin_apps_equipment.Filter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usage_type', models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.Camera')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cameramigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_to', to='astrobin_apps_equipment.Camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessoryMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_gear', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_from', to='astrobin.Accessory')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accessorymigrationrecords', to='astrobin.Image')),
                ('to_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records_as_to', to='astrobin_apps_equipment.Accessory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
