# Generated by Django 2.2.24 on 2022-05-18 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0064_add_migration_records'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessorymigrationrecord',
            unique_together={('image', 'from_gear')},
        ),
        migrations.AlterUniqueTogether(
            name='cameramigrationrecord',
            unique_together={('image', 'from_gear', 'usage_type')},
        ),
        migrations.AlterUniqueTogether(
            name='filtermigrationrecord',
            unique_together={('image', 'from_gear')},
        ),
        migrations.AlterUniqueTogether(
            name='mountmigrationrecord',
            unique_together={('image', 'from_gear')},
        ),
        migrations.AlterUniqueTogether(
            name='softwaremigrationrecord',
            unique_together={('image', 'from_gear')},
        ),
        migrations.AlterUniqueTogether(
            name='telescopemigrationrecord',
            unique_together={('image', 'from_gear', 'usage_type')},
        ),
    ]
