# Generated by Django 2.2.24 on 2022-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0066_remove_cameraeditproposal_create_modified_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('brand', 'name', 'modified', 'cooled')},
        ),
    ]
