# Generated by Django 2.2.24 on 2022-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0067_alter_unique_constraints_of_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cooled',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Cooled'),
        ),
        migrations.AlterField(
            model_name='cameraeditproposal',
            name='cooled',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Cooled'),
        ),
    ]
