# Generated by Django 2.2.24 on 2022-06-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0068_add_default_value_to_camera_cooled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='reviewer_rejection_duplicate_of',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
