# Generated by Django 2.2.24 on 2022-06-07 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0070_add_filter_type_uv_ir_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='other_size',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='filtereditproposal',
            name='other_size',
        ),
        migrations.RemoveField(
            model_name='filtereditproposal',
            name='size',
        ),
    ]
