# Generated by Django 2.2.24 on 2022-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0071_remove_filter_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
