# Generated by Django 2.2.24 on 2022-06-16 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0074_add_user_and_image_counts_to_equipment_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessorymigrationrecord',
            unique_together={('image', 'from_gear', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='cameramigrationrecord',
            unique_together={('image', 'from_gear', 'usage_type', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='focalreducermigrationrecord',
            unique_together={('image', 'from_gear', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='mountmigrationrecord',
            unique_together={('image', 'from_gear', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='softwaremigrationrecord',
            unique_together={('image', 'from_gear', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='telescopemigrationrecord',
            unique_together={('image', 'from_gear', 'usage_type', 'deleted')},
        ),
    ]
