# Generated by Django 2.2.24 on 2022-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0075_add_deleted_to_unique_constraint_or_migration_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbrand',
            name='image_count',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipmentbrand',
            name='last_added_or_removed_from_image',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipmentbrand',
            name='user_count',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
