# Generated by Django 2.2.24 on 2022-06-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0076_add_index_fields_to_equipment_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='reviewer_rejection_duplicate_of_klass',
            field=models.CharField(choices=[('SENSOR', 'Sensor'), ('CAMERA', 'Camera'), ('TELESCOPE', 'Telescope'), ('MOUNT', 'Mount'), ('FILTER', 'Filter'), ('ACCESSORY', 'Accessory'), ('SOFTWARE', 'Software')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='reviewer_rejection_duplicate_of_usage_type',
            field=models.CharField(choices=[('IMAGING', 'Imaging'), ('GUIDING', 'Guiding')], max_length=16, null=True),
        ),
    ]
