# Generated by Django 2.2.24 on 2022-06-21 07:52

import django.db.models.deletion
from annoying.functions import get_object_or_None
from django.db import migrations, models
from django.db.models import Q

from astrobin_apps_equipment.models import Camera
from astrobin_apps_equipment.services.camera_service import CameraService


def migrate_dslr_and_mirrorless_variants(apps, schema_editor):
    CameraModel = apps.get_model('astrobin_apps_equipment', 'Camera')

    cameras = CameraModel.objects.filter(
        CameraService.variant_inclusion_query()
    )

    camera: Camera
    for camera in cameras:
        base_camera = get_object_or_None(
            CameraModel,
            Q(brand=camera.brand) & Q(name=camera.name) & CameraService.variant_exclusion_query()
        )
        if base_camera:
            camera.variant_of = base_camera
            camera.save()


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0077_add_equipment_item_duplicate_klass_and_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Accessory'
            ),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Accessory'
            ),
        ),
        migrations.AddField(
            model_name='camera',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Camera'
            ),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Camera'
            ),
        ),
        migrations.AddField(
            model_name='filter',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Filter'
            ),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Filter'
            ),
        ),
        migrations.AddField(
            model_name='mount',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Mount'
            ),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Mount'
            ),
        ),
        migrations.AddField(
            model_name='sensor',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Sensor'
            ),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Sensor'
            ),
        ),
        migrations.AddField(
            model_name='software',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Software'
            ),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Software'
            ),
        ),
        migrations.AddField(
            model_name='telescope',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Telescope'
            ),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Telescope'
            ),
        ),

        migrations.RunPython(migrate_dslr_and_mirrorless_variants, None)
    ]
