# Generated by Django 2.2.24 on 2022-06-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0077_add_equipment_item_duplicate_klass_and_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Accessory'
            ),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Accessory'
            ),
        ),
        migrations.AddField(
            model_name='camera',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Camera'
            ),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Camera'
            ),
        ),
        migrations.AddField(
            model_name='filter',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Filter'
            ),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Filter'
            ),
        ),
        migrations.AddField(
            model_name='mount',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Mount'
            ),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Mount'
            ),
        ),
        migrations.AddField(
            model_name='sensor',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Sensor'
            ),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Sensor'
            ),
        ),
        migrations.AddField(
            model_name='software',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Software'
            ),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Software'
            ),
        ),
        migrations.AddField(
            model_name='telescope',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants',
                to='astrobin_apps_equipment.Telescope'
            ),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='variant_of',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='variants_in_edit_proposals', to='astrobin_apps_equipment.Telescope'
            ),
        ),
    ]
