# Generated by Django 2.2.24 on 2022-06-24 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0079_deepskyacquisitionmigrationrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filtermigrationrecord',
            unique_together={('image', 'from_gear', 'deleted')},
        ),
    ]
