# Generated by Django 2.2.24 on 2022-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0082_add_item_and_edit_proposal_locks'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='community_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
