# Generated by Django 2.2.24 on 2022-06-28 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0083_add_community_notes_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='accessoryeditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='cameraeditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='filtereditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='mount',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='mounteditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='sensoreditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='softwareeditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='telescope',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
        migrations.RenameField(
            model_name='telescopeeditproposal',
            old_name='reviewer_timestamp',
            new_name='reviewer_lock_timestamp',
        ),
    ]
