# Generated by Django 2.2.24 on 2022-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0087_add_search_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentpreset',
            name='remote_source',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Remote data source'),
        ),
    ]
