# Generated by Django 2.2.24 on 2022-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0090_make_filter_size_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.CharField(choices=[('COMPUTER', 'Computer'), ('DEW_MITIGATION', 'Dew mitigation'), ('FIELD_DEROTATOR', 'FIELD_DEROTATOR'), ('FILTER_WHEEL', 'Filter wheel'), ('FLAT_BOX', 'Flat box'), ('FOCAL_MODIFIED_FIELD_CORRECTOR', 'Focal modified / field corrector'), ('FOCUSER', 'Focuser'), ('OAG', 'Off-axis guider'), ('OBSERVATORY_CONTROL', 'Observatory control'), ('OBSERVATORY_DOME', 'Observatory dome'), ('POWER_DISTRIBUTION', 'Power distribution'), ('WEATHER_MONITORING', 'Weather monitoring'), ('OTHER', 'Other')], default='OTHER', max_length=32, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='type',
            field=models.CharField(choices=[('COMPUTER', 'Computer'), ('DEW_MITIGATION', 'Dew mitigation'), ('FIELD_DEROTATOR', 'FIELD_DEROTATOR'), ('FILTER_WHEEL', 'Filter wheel'), ('FLAT_BOX', 'Flat box'), ('FOCAL_MODIFIED_FIELD_CORRECTOR', 'Focal modified / field corrector'), ('FOCUSER', 'Focuser'), ('OAG', 'Off-axis guider'), ('OBSERVATORY_CONTROL', 'Observatory control'), ('OBSERVATORY_DOME', 'Observatory dome'), ('POWER_DISTRIBUTION', 'Power distribution'), ('WEATHER_MONITORING', 'Weather monitoring'), ('OTHER', 'Other')], default='OTHER', max_length=32, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
