# Generated by Django 2.2.24 on 2022-07-18 07:09

from django.db import migrations


def make_null_values_zeros(apps, schema_editor):
    ModelClass = apps.get_model('astrobin_apps_equipment', 'EquipmentBrand')
    ModelClass.objects.filter(user_count__isnull=True).update(user_count=0)
    ModelClass.objects.filter(image_count__isnull=True).update(image_count=0)


def revert_make_null_values_zeros(apps, schema_editor):
    ModelClass = apps.get_model('astrobin_apps_equipment', 'EquipmentBrand')
    ModelClass.objects.filter(user_count=0).update(user_count=None)
    ModelClass.objects.filter(image_count=0).update(image_count=None)


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0095_make_equipment_user_and_image_count_default_to_zero'),
    ]

    operations = [
        migrations.RunPython(
            make_null_values_zeros,
            revert_make_null_values_zeros
        ),
    ]
