# Generated by Django 2.2.24 on 2022-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0096_convert_brand_user_and_image_count_from_null_to_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='image_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='equipmentbrand',
            name='user_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
