# Generated by Django 2.2.24 on 2022-07-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0097_make_brand_user_and_image_count_default_to_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_accessorys_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_accessoryeditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_accessoryeditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='camera',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_cameras_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_cameraeditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_cameraeditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='filter',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_filters_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_filtereditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_filtereditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='mount',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_mounts_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_mounteditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_mounteditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='sensor',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_sensors_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_sensoreditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_sensoreditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='software',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_softwares_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_softwareeditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_softwareeditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='telescope',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_telescopes_assigned_for_review', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_telescopeeditproposals_assigned_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='edit_proposal_assignee',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_telescopeeditproposals_assigned_edit_proposal_for_review',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
