# Generated by Django 2.2.24 on 2022-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0099_rename_field_derotator'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='frozen_as_ambiguous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
