# Generated by Django 2.2.24 on 2022-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0100_add_frozen_as_ambiguous_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='image_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='equipmentbrand',
            name='user_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
