# Generated by Django 2.2.24 on 2022-07-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0101_make_brand_user_and_image_counts_non_small'),
        ('pybb', '0006_forum_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_accessory_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='accessoryeditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_accessoryeditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='camera',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_camera_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='cameraeditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_cameraeditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='filter',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_filter_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='filtereditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_filtereditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='mount',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_mount_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='mounteditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_mounteditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='sensor',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_sensor_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='sensoreditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_sensoreditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='software',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_software_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='softwareeditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_softwareeditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='telescope',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_telescope_equipment_item', to='pybb.Forum'
            ),
        ),
        migrations.AddField(
            model_name='telescopeeditproposal',
            name='forum',
            field=models.OneToOneField(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='astrobin_apps_equipment_telescopeeditproposal_equipment_item', to='pybb.Forum'
            ),
        ),
    ]
