# Generated by Django 2.2.24 on 2022-08-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('astrobin_apps_equipment', '0104_make_full_well_capacity_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorymigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='accessorymigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameramigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='cameramigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filtermigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='filtermigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focalreducermigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='focalreducermigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mountmigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='mountmigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwaremigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='softwaremigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telescopemigrationrecord',
            name='to_item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AddField(
            model_name='telescopemigrationrecord',
            name='to_item_object_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
