# Generated by Django 2.2.24 on 2022-08-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0105_add_generic_gear_migration_record_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorymigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Accessory'
            ),
        ),
        migrations.AlterField(
            model_name='cameramigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Camera'
            ),
        ),
        migrations.AlterField(
            model_name='focalreducermigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Accessory'
            ),
        ),
        migrations.AlterField(
            model_name='filtermigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Filter'
            ),
        ),
        migrations.AlterField(
            model_name='mountmigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Mount'
            ),
        ),
        migrations.AlterField(
            model_name='softwaremigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Software'
            ),
        ),
        migrations.AlterField(
            model_name='telescopemigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_as_to', to='astrobin_apps_equipment.Telescope'
            ),
        ),
    ]
