# Generated by Django 2.2.24 on 2022-09-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0106_make_specific_gear_migration_target_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focalreducermigrationrecord',
            name='to_item',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='migration_records_from_focal_reducers_as_to', to='astrobin_apps_equipment.Accessory'
            ),
        ),
    ]
