# Generated by Django 2.2.24 on 2022-09-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0107_fix_related_name_of_focal_reducer_migration_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
