# Generated by Django 2.2.24 on 2022-09-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('astrobin_apps_equipment', '0108_equipmentitemlisting_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='item_content_type',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='item_object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
