# Generated by Django 2.2.24 on 2022-10-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0109_add_equipment_item_listing_content_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitemlisting',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='equipmentitemlisting',
            name='url_de',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
