# Generated by Django 2.2.24 on 2022-10-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0110_increase_size_of_equipment_item_listing_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='sensor',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='astrobin_apps_equipment_sensor_cameras', to='astrobin_apps_equipment.Sensor',
                verbose_name='Sensor'
            ),
        ),
        migrations.AlterField(
            model_name='cameraeditproposal',
            name='sensor',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='astrobin_apps_equipment_sensor_cameraeditproposals', to='astrobin_apps_equipment.Sensor',
                verbose_name='Sensor'
            ),
        ),
    ]
