# Generated by Django 2.2.24 on 2023-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('astrobin_apps_equipment', '0113_add_maksutov_newtonian_telescope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='stock_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitemlisting',
            name='stock_status',
            field=models.CharField(blank=True,
                choices=[('UNKNOWN', 'Unknown'), ('BACK_ORDER', 'Back order'), ('IN_STOCK', 'In stock'),
                         ('OUT_OF_STOCK', 'Out of stock')], max_length=16, null=True
            ),
        ),
    ]
