# Generated by Django 2.2.24 on 2023-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0116_add_marketplace_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
