# Generated by Django 2.2.24 on 2023-10-07 14:03

import common.upload_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0116_equipmentitemmarketplacefeedback_equipmentitemmarketplacelisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItemMarketplaceListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('image_file', models.ImageField(height_field='h', max_length=256, null=True, upload_to=common.upload_paths.marketplace_listing_upload_path, width_field='w')),
                ('w', models.PositiveIntegerField(default=0, editable=False)),
                ('h', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='astrobin_apps_equipment.EquipmentItemMarketplaceListing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_marketplace_listing_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
