# Generated by Django 2.2.24 on 2023-10-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0117_equipmentitemmarketplacelisting_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='hash',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='hash',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitemimage',
            name='hash',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
