# Generated by Django 2.2.24 on 2023-12-11 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0120_update_marketplace_line_item_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItemMarketplaceOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_item', models.ForeignKey(
                    editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offers',
                    to='astrobin_apps_equipment.EquipmentItemMarketplaceListingLineItem'
                )),
                ('listing', models.ForeignKey(
                    editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='offers',
                    to='astrobin_apps_equipment.EquipmentItemMarketplaceListing'
                )),
                ('user', models.ForeignKey(
                    editable=False, on_delete=django.db.models.deletion.CASCADE,
                    related_name='equipment_item_marketplace_listings_offers', to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
