# Generated by Django 2.2.24 on 2023-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0120_equipmentitemmarketplaceprivateconversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitemmarketplacelisting',
            options={'ordering': ['-approved', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='equipmentitemmarketplacelistinglineitem',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='equipmentitemmarketplacelisting',
            index=models.Index(fields=['approved', 'updated'], name='astrobin_ap_approve_62e715_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitemmarketplacelisting',
            index=models.Index(fields=['country'], name='astrobin_ap_country_c4caa4_idx'),
        ),
    ]
