# Generated by Django 2.2.24 on 2023-12-14 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0121_add_marketplace_listing_approved_field_ordering_and_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitemmarketplaceprivateconversation',
            options={'ordering': ('created',)},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplaceprivateconversation',
            unique_together={('user', 'listing')},
        ),
    ]
