# Generated by Django 2.2.24 on 2023-12-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0124_add_ordering_and_unique_together_to_marketplace_private_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitemmarketplaceprivateconversation',
            name='deleted',
        ),
    ]
