# Generated by Django 2.2.24 on 2023-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0124_add_last_access_dates_to_private_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='bundle_sale_only',
            field=models.BooleanField(default=False),
        ),
    ]
