# Generated by Django 2.2.24 on 2023-12-15 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0125_remove_equipmentitemmarketplaceprivateconversation_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplaceprivateconversation',
            name='listing_user_last_accessed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplaceprivateconversation',
            name='user_last_accessed',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
    ]
