# Generated by Django 2.2.24 on 2023-12-18 12:55

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0125_equipmentitemmarketplacelisting_bundle_sale_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitemimage',
            name='thumbnail_file',
            field=models.ImageField(height_field='thumbnail_h', max_length=256, null=True, upload_to=common.upload_paths.marketplace_listing_thumbnail_upload_path, width_field='thumbnail_w'),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitemimage',
            name='thumbnail_h',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitemimage',
            name='thumbnail_w',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
