# Generated by Django 2.2.24 on 2024-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0130_equipmentitemmarketplacelistinglineitem_price_chf'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='item_name',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
