# Generated by Django 2.2.24 on 2024-02-01 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0131_equipmentitemmarketplacelistinglineitem_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitemmarketplaceoffer',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplaceoffer',
            unique_together={('user', 'line_item')},
        ),
    ]
