# Generated by Django 2.2.24 on 2024-02-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0132_add_ordering_and_unique_to_equipmentitemmarketplaceoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplaceoffer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
