# Generated by Django 2.2.24 on 2024-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0133_add_updated_to_equipmentitemmarketplaceoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
