# Generated by Django 2.2.24 on 2024-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0134_equipmentitemmarketplacelisting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplaceoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', editable=False, max_length=10),
        ),
    ]
