# Generated by Django 2.2.24 on 2024-03-23 20:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0135_equipmentitemmarketplaceoffer_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplaceoffer',
            unique_together={('user', 'line_item', 'deleted')},
        ),
    ]
