# Generated by Django 2.2.24 on 2024-03-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0136_add_deleted_to_unique_constraint_of_marketplace_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItemMarketplaceMasterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('status', models.CharField(
                    choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')],
                    default='PENDING', editable=False, max_length=10
                )),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(
                    editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='master_offers',
                    to='astrobin_apps_equipment.EquipmentItemMarketplaceListing'
                )),
                ('user', models.ForeignKey(
                    editable=False, on_delete=django.db.models.deletion.CASCADE,
                    related_name='equipment_item_marketplace_listings_master_offers', to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('user', 'listing', 'deleted')},
            },
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplaceoffer',
            name='master_offer',
            field=models.ForeignKey(
                editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers',
                to='astrobin_apps_equipment.EquipmentItemMarketplaceMasterOffer'
            ),
        ),
    ]
