# Generated by Django 2.2.24 on 2024-03-27 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0137_add_marketplace_master_offer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplacemasteroffer',
            unique_together={('user', 'listing')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplaceoffer',
            unique_together={('user', 'line_item')},
        ),
        migrations.RemoveField(
            model_name='equipmentitemmarketplacemasteroffer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='equipmentitemmarketplaceoffer',
            name='deleted',
        ),
    ]
