# Generated by Django 2.2.24 on 2024-04-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0138_make_offer_models_non_soft_deleteable'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='item_plain_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='item_content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'
            ),
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='item_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
