# Generated by Django 2.2.24 on 2024-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0139_add_item_plain_text_to_line_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitemmarketplacefeedback',
            name='text',
        ),
    ]
