# Generated by Django 2.2.24 on 2024-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0140_remove_equipmentitemmarketplacefeedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='rate_seller_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
