# Generated by Django 2.2.24 on 2024-05-14 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0141_equipmentitemmarketplacelistinglineitem_rate_seller_reminder_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitemmarketplacefeedback',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplacefeedback',
            unique_together={('user', 'line_item', 'category')},
        ),
    ]
