# Generated by Django 2.2.24 on 2024-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0143_equipmentitemmarketplacelisting_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='first_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
