# Generated by Django 2.2.24 on 2024-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0144_equipmentitemmarketplacelisting_first_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='target_type',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer')], default='SELLER', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplacefeedback',
            name='category',
            field=models.CharField(
                choices=[('COMMUNICATION', 'Communication and friendliness'), ('SPEED', 'Speed of delivery/payment'),
                         ('ACCURACY', 'Accuracy of item descriptions'), ('PACKAGING', 'Packaging quality')],
                max_length=16
            ),
        ),
    ]
