# Generated by Django 2.2.24 on 2024-05-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0145_add_support_for_buyer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelisting',
            name='expired_notification_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
