# Generated by Django 2.2.24 on 2024-05-22 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0146_equipmentitemmarketplacelisting_expired_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='recipient',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='equipment_item_marketplace_listings_feedbacks_received', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplacefeedback',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='equipment_item_marketplace_listings_feedbacks_given', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
