# Generated by Django 2.2.24 on 2024-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0147_add_marketplace_feedback_recipient_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='mark_as_sold_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
