# Generated by Django 2.2.24 on 2024-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0149_equipmentitemmarketplacelistinglineitem_rate_buyer_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitemmarketplacemasteroffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('RETRACTED', 'RETRACTED')], default='PENDING', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplaceoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('RETRACTED', 'RETRACTED')], default='PENDING', editable=False, max_length=10),
        ),
    ]
