# Generated by Django 2.2.24 on 2024-06-06 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0152_add_uuid_field_to_marketplace_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitemmarketplacemasteroffer',
            name='master_offer_uuid',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplacemasteroffer',
            unique_together={('user', 'listing', 'master_offer_uuid')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplaceoffer',
            unique_together={('user', 'line_item', 'master_offer_uuid')},
        ),
    ]
