# Generated by Django 2.2.24 on 2024-06-24 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0154_remove_equipmentitemmarketplacelisting_bundle_sale_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplaceoffer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
