# Generated by Django 2.2.24 on 2024-06-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0155_add_min_value_validator_to_line_item_price_and_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
