# Generated by Django 2.2.24 on 2024-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0156_equipmentitemmarketplacefeedback_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
