# Generated by Django 2.2.24 on 2024-06-26 10:39

from django.conf import settings
from django.db import migrations, models


def delete_all_feedbacks(apps, schema_editor):
    feedback_model = apps.get_model('astrobin_apps_equipment', 'EquipmentItemMarketplaceFeedback')
    feedback_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0157_equipmentitemmarketplacefeedback_message'),
    ]

    operations = [
        migrations.RunPython(delete_all_feedbacks),
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='accuracy_value',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='communication_value',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='packaging_value',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='speed_value',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentitemmarketplacefeedback',
            name='value',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive')], max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplacefeedback',
            unique_together={('user', 'line_item')},
        ),
        migrations.RemoveField(
            model_name='equipmentitemmarketplacefeedback',
            name='category',
        ),
    ]
