# Generated by Django 2.2.24 on 2024-06-26 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def delete_all_feedbacks(apps, schema_editor):
    feedback_model = apps.get_model('astrobin_apps_equipment', 'EquipmentItemMarketplaceFeedback')
    feedback_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0159_remove_equipmentitemmarketplacefeedback_value'),
    ]

    operations = [
        migrations.RunPython(delete_all_feedbacks),
        migrations.AddField(
            model_name='equipmentitemmarketplacefeedback',
            name='listing',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='astrobin_apps_equipment.EquipmentItemMarketplaceListing'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='equipmentitemmarketplacefeedback',
            unique_together={('user', 'listing')},
        ),
        migrations.RemoveField(
            model_name='equipmentitemmarketplacefeedback',
            name='line_item',
        ),
    ]
