# Generated by Django 2.2.24 on 2024-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0163_equipmentitemmarketplacelisting_listing_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitemmarketplacelisting',
            options={'ordering': ['-created']},
        ),
    ]
