# Generated by Django 2.2.24 on 2024-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0166_equipmentitemmarketplacelisting_manual_approval_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitemmarketplacelistinglineitem',
            name='shipping_cost_type',
            field=models.CharField(
                choices=[('NO_SHIPPING', 'No shipping'), ('COVERED_BY_SELLER', 'Covered by seller'), ('FIXED', 'Fixed'),
                         ('TO_BE_AGREED', 'To be agreed')], default='FIXED', max_length=32
            ),
        ),
    ]
