# Generated by Django 2.2.24 on 2024-11-14 21:38

import astrobin_apps_equipment.models.equipment_preset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_equipment', '0168_rename_rowe_atkinson_to_rowe_ackermann'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpreset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentpreset',
            name='image_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentpreset',
            name='image_file',
            field=models.ImageField(
                blank=True, null=True, upload_to=astrobin_apps_equipment.models.equipment_preset.image_upload_path
            ),
        ),
        migrations.AddField(
            model_name='equipmentpreset',
            name='total_integration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
