# Generated by Django 2.2.24 on 2025-03-30 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrobin_apps_equipment', '0171_increase_max_digits_of_mount_weight_and_max_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('width_arcseconds', models.FloatField(default=3600.0, verbose_name='Width (arcseconds)')),
                ('height_arcseconds', models.FloatField(default=3600.0, verbose_name='Height (arcseconds)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'user')},
                'verbose_name': 'Measurement Preset',
                'verbose_name_plural': 'Measurement Presets',
            },
        ),
    ]
