# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-09 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesharedfolder',
            name='images',
            field=models.ManyToManyField(to='rawdata.RawImage'),
        ),
        migrations.AlterField(
            model_name='privatesharedfolder',
            name='processed_images',
            field=models.ManyToManyField(blank=True, to='astrobin.Image'),
        ),
        migrations.AlterField(
            model_name='publicdatapool',
            name='images',
            field=models.ManyToManyField(to='rawdata.RawImage'),
        ),
        migrations.AlterField(
            model_name='publicdatapool',
            name='processed_images',
            field=models.ManyToManyField(blank=True, to='astrobin.Image'),
        ),
        migrations.AlterField(
            model_name='rawimage',
            name='image_type',
            field=models.IntegerField(
                choices=[(0, 'Unknown'), (1, 'Light'), (2, 'Offset/Bias'), (3, 'Dark'), (4, 'Flat')], default=0,
                editable=False),
        ),
    ]
