# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import rawdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0002_auto_20171109_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimage',
            name='file',
            field=models.FileField(upload_to=rawdata.models.upload_path),
        ),
        migrations.AlterField(
            model_name='temporaryarchive',
            name='file',
            field=models.FileField(upload_to=rawdata.models.temporary_download_upload_path),
        ),
    ]
