# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLossCompensationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('requested_compensation', models.CharField(choices=[(b'NOT_AFFECTED', "I wasn't really affected by the data loss"), (b'NOT_REQUIRED', "I don't require compensation: I want to support AstroBin"), (b'1_MO_ULTIMATE', 'I would like to try AstroBin Ultimate for free for 1 month'), (b'3_MO_ULTIMATE', 'I feel entitled to AstroBin Ultimate for free for 3 months'), (b'6_MO_ULTIMATE', 'I feel entitled to AstroBin Ultimate for free for 6 months')], help_text='Please indicate if and how much you would like to be compensated.', max_length=14, verbose_name='Requested compensation')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
