# Generated by Django 2.2.24 on 2021-07-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalosscompensationrequest',
            name='requested_compensation',
            field=models.CharField(choices=[('NOT_AFFECTED', "I wasn't really affected by the data loss"), ('NOT_REQUIRED', "I don't require compensation: I want to support AstroBin"), ('1_MO_ULTIMATE', 'I would like to try AstroBin Ultimate for free for 1 month'), ('3_MO_ULTIMATE', 'I feel entitled to AstroBin Ultimate for free for 3 months'), ('6_MO_ULTIMATE', 'I feel entitled to AstroBin Ultimate for free for 6 months')], help_text='Please indicate if and how much you would like to be compensated.', max_length=14, verbose_name='Requested compensation'),
        ),
    ]
