# Generated by Django 2.2.24 on 2023-01-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrobin_apps_premium', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataLossCompensationRequest',
        ),
    ]
