AWSTemplateFormatVersion: '2010-09-09'
Description: AstroBin Parameter store

Parameters:

  AccessKeyIdParameter:
    Type: String

  AdsensePublisherIdParameter:
    Type: String

  AmqpPasswordParameter:
    Type: String

  AstrometryNetApiKeyParameter:
    Type: String

  CloudflareTokenParameter:
    Type: String

  CloudflareZoneIdParameter:
    Type: String

  DjangoSecretKeyParameter:
    Type: String

  ElasticSearchAwsRegionParameter:
    Type: String

  ElasticSearchUrlParameter:
    Type: String

  EmailHostParameter:
    Type: String

  EmailHostPasswordParameter:
    Type: String

  EmailHostPortParameter:
    Type: String
    Default: 465

  EmailHostUserParameter:
    Type: String

  EmailUseSslParameter:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  FlickrApiKeyParameter:
    Type: String

  FlickrSecretParameter:
    Type: String

  GoogleAdsIdParameter:
    Type: String

  GoogleAnalyticsIdParameter:
    Type: String

  PixInsightPasswordParameter:
    Type: String

  PixInsightUsernameParameter:
    Type: String
    Default: AstroBin

  PostgresHostParameter:
    Type: String

  PostgresPasswordParameter:
    Type: String

  PostgresReadReplicaHostParameter:
    Type: String

  SecretAccessKeyParameter:
    Type: String

Resources:

  AccessKeyId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ACCESS_KEY_ID
      Type: String
      Value: !Ref AccessKeyIdParameter

  AdsensePublisherId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ADSENSE_PUBLISHER_ID
      Type: String
      Value: !Ref AdsensePublisherIdParameter

  AmqpAdminPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AMQP_ADMIN_PASSWORD
      Type: String
      Value: !Ref AmqpPasswordParameter

  AmqpPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: AMQP_PASSWORD
      Type: String
      Value: !Ref AmqpPasswordParameter

  AstrometryNetApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ASTROMETRY_NET_API_KEY
      Type: String
      Value: !Ref AstrometryNetApiKeyParameter

  BrokerUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: BROKER_URL
      Type: String
      Value: !Sub
        - amqp://astrobin:${AmqpPassword}@rabbitmq.services.astrobin.com:5672
        - { AmqpPassword: !Ref AmqpPasswordParameter }

  CloudflareToken:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CLOUDFLARE_TOKEN
      Type: String
      Value: !Ref CloudflareTokenParameter

  CloudflareZoneId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CLOUDFLARE_ZONE_ID
      Type: String
      Value: !Ref CloudflareZoneIdParameter

  DjangoSecretKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: DJANGO_SECRET_KEY
      Type: String
      Value: !Ref DjangoSecretKeyParameter

  ElasticSearchAwsRegion:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ELASTIC_SEARCH_AWS_REGION
      Type: String
      Value: !Ref ElasticSearchAwsRegionParameter

  ElasticSearchUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ELASTICSEARCH_URL
      Type: String
      Value: !Ref ElasticSearchUrlParameter

  EmailHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: EMAIL_HOST
      Type: String
      Value: !Ref EmailHostParameter

  EmailHostPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: EMAIL_HOST_PASSWORD
      Type: String
      Value: !Ref EmailHostPasswordParameter

  EmailHostPort:
    Type: AWS::SSM::Parameter
    Properties:
      Name: EMAIL_HOST_PORT
      Type: String
      Value: !Ref EmailHostPortParameter

  EmailHostUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: EMAIL_HOST_USER
      Type: String
      Value: !Ref EmailHostUserParameter

  EmailUseSsl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: EMAIL_USE_SSL
      Type: String
      Value: !Ref EmailUseSslParameter

  FlickrApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: FLICKR_API_KEY
      Type: String
      Value: !Ref FlickrApiKeyParameter

  FlickrSecret:
    Type: AWS::SSM::Parameter
    Properties:
      Name: FLICKR_SECRET
      Type: String
      Value: !Ref FlickrSecretParameter

  GoogleAdsId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: GOOGLE_ADS_ID
      Type: String
      Value: !Ref GoogleAdsIdParameter

  GoogleAnalyticsId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: GOOGLE_ANALYTICS_ID
      Type: String
      Value: REPLACE_ME

  PayPalMerchantId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: PAYPAL_MERCHANT_ID
      Type: String
      Value: !Ref GoogleAnalyticsIdParameter

  PixInsightPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: PIXINSIGHT_PASSWORD
      Type: String
      Value: !Ref PixInsightPasswordParameter

  PixInsightUsername:
    Type: AWS::SSM::Parameter
    Properties:
      Name: PIXINSIGHT_USERNAME
      Type: String
      Value: !Ref PixInsightUsernameParameter

  PostgresHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: POSTGRES_HOST
      Type: String
      Value: !Ref PostgresHostParameter

  PostgresPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: POSTGRES_PASSWORD
      Type: String
      Value: !Ref PostgresPasswordParameter

  PostgresReadReplicaHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: POSTGRES_READ_REPLICA_HOST
      Type: String
      Value: !Ref PostgresReadReplicaHostParameter

  RabbitmqDefaultPass:
    Type: AWS::SSM::Parameter
    Properties:
      Name: RABBITMQ_DEFAULT_PASS
      Type: String
      Value: !Ref AmqpPasswordParameter

  SecretAccessKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SECRET_ACCESS_KEY
      Type: String
      Value: !Ref SecretAccessKeyParameter
