AWSTemplateFormatVersion: '2010-09-09'
Description: AstroBin IAM roles

Resources:

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: astrobin-execution-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'

Outputs:

  ExecutionRole:
    Value: !Ref ExecutionRole
    Export:
      Name: 'ExecutionRole'
