#define ERROR                           1
#define OR                              2
#define XOR                             3
#define AND                             4
#define NOT                             5
#define NEAR                            6
#define ADJ                             7
#define LOVE                            8
#define HATE                            9
#define HATE_AFTER_AND                 10
#define SYNONYM                        11
#define TERM                           12
#define GROUP_TERM                     13
#define PHR_TERM                       14
#define WILD_TERM                      15
#define PARTIAL_TERM                   16
#define BOOLEAN_FILTER                 17
#define RANGE                          18
#define QUOTE                          19
#define BRA                            20
#define KET                            21
#define EMPTY_GROUP_OK                 22
